
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.distantworlds.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.distantworlds.procedures.WiltumCratePropertyValueProviderProcedure;
import net.mcreator.distantworlds.procedures.GarsaleCratePropertyValueProviderProcedure;
import net.mcreator.distantworlds.item.WitherTotemItem;
import net.mcreator.distantworlds.item.WiltumFruitItem;
import net.mcreator.distantworlds.item.WiltumElixirItem;
import net.mcreator.distantworlds.item.WiltumCrateItem;
import net.mcreator.distantworlds.item.WiltumCocktailItem;
import net.mcreator.distantworlds.item.VairisSwordItem;
import net.mcreator.distantworlds.item.VairisItem;
import net.mcreator.distantworlds.item.VairisCrystalItem;
import net.mcreator.distantworlds.item.UbriciteIngotItem;
import net.mcreator.distantworlds.item.UbriciteHammerItem;
import net.mcreator.distantworlds.item.UbriciteCrystalItem;
import net.mcreator.distantworlds.item.UbriciteArmorItem;
import net.mcreator.distantworlds.item.StickyGarsaleBarkItem;
import net.mcreator.distantworlds.item.SalmoranTreatItem;
import net.mcreator.distantworlds.item.SalmoranScalesItem;
import net.mcreator.distantworlds.item.SalmoranMeatItem;
import net.mcreator.distantworlds.item.SalmoranEyeItem;
import net.mcreator.distantworlds.item.SalmoranCrownItem;
import net.mcreator.distantworlds.item.SalmoranArmorItem;
import net.mcreator.distantworlds.item.ReveliteSwordItem;
import net.mcreator.distantworlds.item.ReveliteShovelItem;
import net.mcreator.distantworlds.item.RevelitePickaxeItem;
import net.mcreator.distantworlds.item.ReveliteHoeItem;
import net.mcreator.distantworlds.item.ReveliteAxeItem;
import net.mcreator.distantworlds.item.ReturnRingItem;
import net.mcreator.distantworlds.item.RawWokamireItem;
import net.mcreator.distantworlds.item.RawVairisItem;
import net.mcreator.distantworlds.item.RawHelystItem;
import net.mcreator.distantworlds.item.RawFironItem;
import net.mcreator.distantworlds.item.RawDaliteItem;
import net.mcreator.distantworlds.item.RawCureliteItem;
import net.mcreator.distantworlds.item.NoarhornSpikeItem;
import net.mcreator.distantworlds.item.NoarhornMeatItem;
import net.mcreator.distantworlds.item.NoarhornGlovesItem;
import net.mcreator.distantworlds.item.NoarhornAxeItem;
import net.mcreator.distantworlds.item.NoarhornArmorItem;
import net.mcreator.distantworlds.item.MoltenFraliteItem;
import net.mcreator.distantworlds.item.ModuleRagingSparkItem;
import net.mcreator.distantworlds.item.ModuleRagingFlameItem;
import net.mcreator.distantworlds.item.ModuleIncreasedStorageItem;
import net.mcreator.distantworlds.item.ModuleFlowFilterItem;
import net.mcreator.distantworlds.item.ModuleFlowAmplificationItem;
import net.mcreator.distantworlds.item.ModuleEmptyItem;
import net.mcreator.distantworlds.item.ModuleCoreStabilizationItem;
import net.mcreator.distantworlds.item.ModuleCoreDestabilizationItem;
import net.mcreator.distantworlds.item.ModuleCharmedPedestalItem;
import net.mcreator.distantworlds.item.ModuleCalmSparkItem;
import net.mcreator.distantworlds.item.ModuleCalmFlameItem;
import net.mcreator.distantworlds.item.LithumSwordItem;
import net.mcreator.distantworlds.item.LithumShovelItem;
import net.mcreator.distantworlds.item.LithumPickaxeItem;
import net.mcreator.distantworlds.item.LithumHoeItem;
import net.mcreator.distantworlds.item.LithumAxeItem;
import net.mcreator.distantworlds.item.HelystSwordItem;
import net.mcreator.distantworlds.item.HelystShovelItem;
import net.mcreator.distantworlds.item.HelystPickaxeItem;
import net.mcreator.distantworlds.item.HelystNuggetItem;
import net.mcreator.distantworlds.item.HelystItem;
import net.mcreator.distantworlds.item.HelystHoeItem;
import net.mcreator.distantworlds.item.HelystCrystalItem;
import net.mcreator.distantworlds.item.HelystBellItem;
import net.mcreator.distantworlds.item.HelystAxeItem;
import net.mcreator.distantworlds.item.GlowingPollenJarItem;
import net.mcreator.distantworlds.item.GlowingPollenItem;
import net.mcreator.distantworlds.item.GlisteringWiltumFruitItem;
import net.mcreator.distantworlds.item.GlisteringWiltumElixirItem;
import net.mcreator.distantworlds.item.GlisteringGarsaleFruitItem;
import net.mcreator.distantworlds.item.GlisteringGarsaleElixirItem;
import net.mcreator.distantworlds.item.GarsaleSlimeItem;
import net.mcreator.distantworlds.item.GarsaleFruitItem;
import net.mcreator.distantworlds.item.GarsaleElixirItem;
import net.mcreator.distantworlds.item.GarsaleCrateItem;
import net.mcreator.distantworlds.item.GarhennaPouchItem;
import net.mcreator.distantworlds.item.GarhennaEyeItem;
import net.mcreator.distantworlds.item.GarhennaBookItem;
import net.mcreator.distantworlds.item.FuziannaJellyItem;
import net.mcreator.distantworlds.item.FraliteSwordItem;
import net.mcreator.distantworlds.item.FraliteShovelItem;
import net.mcreator.distantworlds.item.FralitePickaxeItem;
import net.mcreator.distantworlds.item.FraliteHoeItem;
import net.mcreator.distantworlds.item.FraliteHeartItem;
import net.mcreator.distantworlds.item.FraliteBallItem;
import net.mcreator.distantworlds.item.FraliteAxeItem;
import net.mcreator.distantworlds.item.FironSwordItem;
import net.mcreator.distantworlds.item.FironShovelItem;
import net.mcreator.distantworlds.item.FironPickaxeItem;
import net.mcreator.distantworlds.item.FironNuggetItem;
import net.mcreator.distantworlds.item.FironMultitoolItem;
import net.mcreator.distantworlds.item.FironItem;
import net.mcreator.distantworlds.item.FironIngotItem;
import net.mcreator.distantworlds.item.FironHoeItem;
import net.mcreator.distantworlds.item.FironAxeItem;
import net.mcreator.distantworlds.item.DistantWorldsBookItem;
import net.mcreator.distantworlds.item.DaliteStorageInitialItem;
import net.mcreator.distantworlds.item.DaliteStorageExtendedItem;
import net.mcreator.distantworlds.item.DaliteStorageAdvancedItem;
import net.mcreator.distantworlds.item.DaliteStaffItem;
import net.mcreator.distantworlds.item.DaliteNuggetItem;
import net.mcreator.distantworlds.item.DaliteIndicatorItem;
import net.mcreator.distantworlds.item.DaliteCrystalItem;
import net.mcreator.distantworlds.item.CureliteTorchItem;
import net.mcreator.distantworlds.item.CureliteItem;
import net.mcreator.distantworlds.item.CulafiteShroomerCapItem;
import net.mcreator.distantworlds.item.CulafiteMushroomStewItem;
import net.mcreator.distantworlds.item.CulafiteMushroomOnAStickItem;
import net.mcreator.distantworlds.item.CulafiteElixirItem;
import net.mcreator.distantworlds.item.CookedSalmoranMeatItem;
import net.mcreator.distantworlds.item.CookedNoarhornMeatItem;
import net.mcreator.distantworlds.item.CompletedGarhennaResearchesItem;
import net.mcreator.distantworlds.item.ChargedWitherTotemItem;
import net.mcreator.distantworlds.item.AsmuldaPieItem;
import net.mcreator.distantworlds.item.AsmuldaElixirItem;
import net.mcreator.distantworlds.item.AsmuldaBerriesItem;
import net.mcreator.distantworlds.item.AncientGarhennaPapersItem;
import net.mcreator.distantworlds.DistantWorldsMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class DistantWorldsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, DistantWorldsMod.MODID);
	public static final RegistryObject<Item> RETURN_RING = REGISTRY.register("return_ring", () -> new ReturnRingItem());
	public static final RegistryObject<Item> GARHENNA_EYE = REGISTRY.register("garhenna_eye", () -> new GarhennaEyeItem());
	public static final RegistryObject<Item> WITHER_TOTEM = REGISTRY.register("wither_totem", () -> new WitherTotemItem());
	public static final RegistryObject<Item> CHARGED_WITHER_TOTEM = REGISTRY.register("charged_wither_totem", () -> new ChargedWitherTotemItem());
	public static final RegistryObject<Item> DALITE_INDICATOR = REGISTRY.register("dalite_indicator", () -> new DaliteIndicatorItem());
	public static final RegistryObject<Item> ANCIENT_GARHENNA_PAPERS = REGISTRY.register("ancient_garhenna_papers", () -> new AncientGarhennaPapersItem());
	public static final RegistryObject<Item> GARHENNA_POUCH = REGISTRY.register("garhenna_pouch", () -> new GarhennaPouchItem());
	public static final RegistryObject<Item> ASMULDA_BERRIES = REGISTRY.register("asmulda_berries", () -> new AsmuldaBerriesItem());
	public static final RegistryObject<Item> ASMULDA_PIE = REGISTRY.register("asmulda_pie", () -> new AsmuldaPieItem());
	public static final RegistryObject<Item> ASMULDA_ELIXIR = REGISTRY.register("asmulda_elixir", () -> new AsmuldaElixirItem());
	public static final RegistryObject<Item> ASMULDA_BERRIES_BOX = block(DistantWorldsModBlocks.ASMULDA_BERRIES_BOX);
	public static final RegistryObject<Item> GARSALE_SLIME = REGISTRY.register("garsale_slime", () -> new GarsaleSlimeItem());
	public static final RegistryObject<Item> GARSALE_FRUIT = REGISTRY.register("garsale_fruit", () -> new GarsaleFruitItem());
	public static final RegistryObject<Item> GARSALE_CAKE = block(DistantWorldsModBlocks.GARSALE_CAKE);
	public static final RegistryObject<Item> GARSALE_ELIXIR = REGISTRY.register("garsale_elixir", () -> new GarsaleElixirItem());
	public static final RegistryObject<Item> GARSALE_FRUIT_BOX = block(DistantWorldsModBlocks.GARSALE_FRUIT_BOX);
	public static final RegistryObject<Item> FUZIANNA_JELLY = REGISTRY.register("fuzianna_jelly", () -> new FuziannaJellyItem());
	public static final RegistryObject<Item> WILTUM_FRUIT = REGISTRY.register("wiltum_fruit", () -> new WiltumFruitItem());
	public static final RegistryObject<Item> WILTUM_COCKTAIL = REGISTRY.register("wiltum_cocktail", () -> new WiltumCocktailItem());
	public static final RegistryObject<Item> WILTUM_ELIXIR = REGISTRY.register("wiltum_elixir", () -> new WiltumElixirItem());
	public static final RegistryObject<Item> WILTUM_FRUIT_BOX = block(DistantWorldsModBlocks.WILTUM_FRUIT_BOX);
	public static final RegistryObject<Item> RAW_WOKAMIRE = REGISTRY.register("raw_wokamire", () -> new RawWokamireItem());
	public static final RegistryObject<Item> SALMORAN_TREAT = REGISTRY.register("salmoran_treat", () -> new SalmoranTreatItem());
	public static final RegistryObject<Item> CULAFITE_SHROOMER_CAP = REGISTRY.register("culafite_shroomer_cap", () -> new CulafiteShroomerCapItem());
	public static final RegistryObject<Item> CULAFITE_MUSHROOM_STEW = REGISTRY.register("culafite_mushroom_stew", () -> new CulafiteMushroomStewItem());
	public static final RegistryObject<Item> CULAFITE_ELIXIR = REGISTRY.register("culafite_elixir", () -> new CulafiteElixirItem());
	public static final RegistryObject<Item> CULAFITE_MUSHROOMS_BOX = block(DistantWorldsModBlocks.CULAFITE_MUSHROOMS_BOX);
	public static final RegistryObject<Item> MOLTEN_FRALITE = REGISTRY.register("molten_fralite", () -> new MoltenFraliteItem());
	public static final RegistryObject<Item> FRALITE_HEART = REGISTRY.register("fralite_heart", () -> new FraliteHeartItem());
	public static final RegistryObject<Item> NOARHORN_MEAT = REGISTRY.register("noarhorn_meat", () -> new NoarhornMeatItem());
	public static final RegistryObject<Item> COOKED_NOARHORN_MEAT = REGISTRY.register("cooked_noarhorn_meat", () -> new CookedNoarhornMeatItem());
	public static final RegistryObject<Item> NOARHORN_SPIKE = REGISTRY.register("noarhorn_spike", () -> new NoarhornSpikeItem());
	public static final RegistryObject<Item> NOARHORN_GLOVES = REGISTRY.register("noarhorn_gloves", () -> new NoarhornGlovesItem());
	public static final RegistryObject<Item> NOARHORN_SPIKES_BLOCK = block(DistantWorldsModBlocks.NOARHORN_SPIKES_BLOCK);
	public static final RegistryObject<Item> UBRICITE_CRYSTAL = REGISTRY.register("ubricite_crystal", () -> new UbriciteCrystalItem());
	public static final RegistryObject<Item> UBRICITE_INGOT = REGISTRY.register("ubricite_ingot", () -> new UbriciteIngotItem());
	public static final RegistryObject<Item> SALMORAN_SCALES = REGISTRY.register("salmoran_scales", () -> new SalmoranScalesItem());
	public static final RegistryObject<Item> SALMORAN_MEAT = REGISTRY.register("salmoran_meat", () -> new SalmoranMeatItem());
	public static final RegistryObject<Item> COOKED_SALMORAN_MEAT = REGISTRY.register("cooked_salmoran_meat", () -> new CookedSalmoranMeatItem());
	public static final RegistryObject<Item> SALMORAN_EYE = REGISTRY.register("salmoran_eye", () -> new SalmoranEyeItem());
	public static final RegistryObject<Item> SALMORAN_CROWN = REGISTRY.register("salmoran_crown", () -> new SalmoranCrownItem());
	public static final RegistryObject<Item> SALMORAN_EGG = block(DistantWorldsModBlocks.SALMORAN_EGG);
	public static final RegistryObject<Item> STICKY_GARSALE_BARK = REGISTRY.register("sticky_garsale_bark", () -> new StickyGarsaleBarkItem());
	public static final RegistryObject<Item> GLOWING_POLLEN = REGISTRY.register("glowing_pollen", () -> new GlowingPollenItem());
	public static final RegistryObject<Item> GLOWING_POLLEN_JAR = REGISTRY.register("glowing_pollen_jar", () -> new GlowingPollenJarItem());
	public static final RegistryObject<Item> RAW_VAIRIS = REGISTRY.register("raw_vairis", () -> new RawVairisItem());
	public static final RegistryObject<Item> VAIRIS_CRYSTAL = REGISTRY.register("vairis_crystal", () -> new VairisCrystalItem());
	public static final RegistryObject<Item> RAW_VAIRIS_BLOCK = block(DistantWorldsModBlocks.RAW_VAIRIS_BLOCK);
	public static final RegistryObject<Item> VAIRIS_BLOCK = block(DistantWorldsModBlocks.VAIRIS_BLOCK);
	public static final RegistryObject<Item> RAW_CURELITE = REGISTRY.register("raw_curelite", () -> new RawCureliteItem());
	public static final RegistryObject<Item> CURELITE = REGISTRY.register("curelite", () -> new CureliteItem());
	public static final RegistryObject<Item> RAW_CURELITE_BLOCK = block(DistantWorldsModBlocks.RAW_CURELITE_BLOCK);
	public static final RegistryObject<Item> CURELITE_BLOCK = block(DistantWorldsModBlocks.CURELITE_BLOCK);
	public static final RegistryObject<Item> RAW_DALITE = REGISTRY.register("raw_dalite", () -> new RawDaliteItem());
	public static final RegistryObject<Item> DALITE_NUGGET = REGISTRY.register("dalite_nugget", () -> new DaliteNuggetItem());
	public static final RegistryObject<Item> DALITE_CRYSTAL = REGISTRY.register("dalite_crystal", () -> new DaliteCrystalItem());
	public static final RegistryObject<Item> RAW_DALITE_BLOCK = block(DistantWorldsModBlocks.RAW_DALITE_BLOCK);
	public static final RegistryObject<Item> DALITE_BLOCK = block(DistantWorldsModBlocks.DALITE_BLOCK);
	public static final RegistryObject<Item> RAW_HELYST = REGISTRY.register("raw_helyst", () -> new RawHelystItem());
	public static final RegistryObject<Item> HELYST_NUGGET = REGISTRY.register("helyst_nugget", () -> new HelystNuggetItem());
	public static final RegistryObject<Item> HELYST_CRYSTAL = REGISTRY.register("helyst_crystal", () -> new HelystCrystalItem());
	public static final RegistryObject<Item> RAW_HELYST_BLOCK = block(DistantWorldsModBlocks.RAW_HELYST_BLOCK);
	public static final RegistryObject<Item> HELYST_BLOCK = block(DistantWorldsModBlocks.HELYST_BLOCK);
	public static final RegistryObject<Item> HELYST_BELL = REGISTRY.register("helyst_bell", () -> new HelystBellItem());
	public static final RegistryObject<Item> RAW_FIRON = REGISTRY.register("raw_firon", () -> new RawFironItem());
	public static final RegistryObject<Item> FIRON_NUGGET = REGISTRY.register("firon_nugget", () -> new FironNuggetItem());
	public static final RegistryObject<Item> FIRON_INGOT = REGISTRY.register("firon_ingot", () -> new FironIngotItem());
	public static final RegistryObject<Item> RAW_FIRON_BLOCK = block(DistantWorldsModBlocks.RAW_FIRON_BLOCK);
	public static final RegistryObject<Item> FIRON_BLOCK = block(DistantWorldsModBlocks.FIRON_BLOCK);
	public static final RegistryObject<Item> GLISTERING_GARSALE_FRUIT = REGISTRY.register("glistering_garsale_fruit", () -> new GlisteringGarsaleFruitItem());
	public static final RegistryObject<Item> GLISTERING_GARSALE_ELIXIR = REGISTRY.register("glistering_garsale_elixir", () -> new GlisteringGarsaleElixirItem());
	public static final RegistryObject<Item> GLISTERING_GARSALE_FRUIT_BOX = block(DistantWorldsModBlocks.GLISTERING_GARSALE_FRUIT_BOX);
	public static final RegistryObject<Item> DALITE_STAFF = REGISTRY.register("dalite_staff", () -> new DaliteStaffItem());
	public static final RegistryObject<Item> MODULE_EMPTY = REGISTRY.register("module_empty", () -> new ModuleEmptyItem());
	public static final RegistryObject<Item> MODULE_CHARMED_PEDESTAL = REGISTRY.register("module_charmed_pedestal", () -> new ModuleCharmedPedestalItem());
	public static final RegistryObject<Item> MODULE_INCREASED_STORAGE = REGISTRY.register("module_increased_storage", () -> new ModuleIncreasedStorageItem());
	public static final RegistryObject<Item> MODULE_CALM_FLAME = REGISTRY.register("module_calm_flame", () -> new ModuleCalmFlameItem());
	public static final RegistryObject<Item> MODULE_RAGING_FLAME = REGISTRY.register("module_raging_flame", () -> new ModuleRagingFlameItem());
	public static final RegistryObject<Item> MODULE_CALM_SPARK = REGISTRY.register("module_calm_spark", () -> new ModuleCalmSparkItem());
	public static final RegistryObject<Item> MODULE_RAGING_SPARK = REGISTRY.register("module_raging_spark", () -> new ModuleRagingSparkItem());
	public static final RegistryObject<Item> MODULE_FLOW_FILTER = REGISTRY.register("module_flow_filter", () -> new ModuleFlowFilterItem());
	public static final RegistryObject<Item> MODULE_FLOW_AMPLIFICATION = REGISTRY.register("module_flow_amplification", () -> new ModuleFlowAmplificationItem());
	public static final RegistryObject<Item> MODULE_CORE_STABILIZATION = REGISTRY.register("module_core_stabilization", () -> new ModuleCoreStabilizationItem());
	public static final RegistryObject<Item> MODULE_CORE_DESTABILIZATION = REGISTRY.register("module_core_destabilization", () -> new ModuleCoreDestabilizationItem());
	public static final RegistryObject<Item> DALITE_STORAGE_INITIAL = REGISTRY.register("dalite_storage_initial", () -> new DaliteStorageInitialItem());
	public static final RegistryObject<Item> DALITE_STORAGE_EXTENDED = REGISTRY.register("dalite_storage_extended", () -> new DaliteStorageExtendedItem());
	public static final RegistryObject<Item> DALITE_STORAGE_ADVANCED = REGISTRY.register("dalite_storage_advanced", () -> new DaliteStorageAdvancedItem());
	public static final RegistryObject<Item> LIFELESS_GRASS = block(DistantWorldsModBlocks.LIFELESS_GRASS);
	public static final RegistryObject<Item> LIFELESS_SPROUTS = block(DistantWorldsModBlocks.LIFELESS_SPROUTS);
	public static final RegistryObject<Item> TALL_LIFELESS_SPROUTS = doubleBlock(DistantWorldsModBlocks.TALL_LIFELESS_SPROUTS);
	public static final RegistryObject<Item> AFOLLA = block(DistantWorldsModBlocks.AFOLLA);
	public static final RegistryObject<Item> WALIS = block(DistantWorldsModBlocks.WALIS);
	public static final RegistryObject<Item> SUWONNA = block(DistantWorldsModBlocks.SUWONNA);
	public static final RegistryObject<Item> APHLAVIS = block(DistantWorldsModBlocks.APHLAVIS);
	public static final RegistryObject<Item> VINRETTY = doubleBlock(DistantWorldsModBlocks.VINRETTY);
	public static final RegistryObject<Item> LAYERED_MUD = block(DistantWorldsModBlocks.LAYERED_MUD);
	public static final RegistryObject<Item> STICKY_SPROUTS = block(DistantWorldsModBlocks.STICKY_SPROUTS);
	public static final RegistryObject<Item> TALL_STICKY_SPROUTS = doubleBlock(DistantWorldsModBlocks.TALL_STICKY_SPROUTS);
	public static final RegistryObject<Item> IROTINE = block(DistantWorldsModBlocks.IROTINE);
	public static final RegistryObject<Item> LAFOSIA = block(DistantWorldsModBlocks.LAFOSIA);
	public static final RegistryObject<Item> PRIFONNA = block(DistantWorldsModBlocks.PRIFONNA);
	public static final RegistryObject<Item> ANEWORT = doubleBlock(DistantWorldsModBlocks.ANEWORT);
	public static final RegistryObject<Item> GARSALE_SAPLING = block(DistantWorldsModBlocks.GARSALE_SAPLING);
	public static final RegistryObject<Item> GARSALE_LEAVES = block(DistantWorldsModBlocks.GARSALE_LEAVES);
	public static final RegistryObject<Item> FLOWERING_GARSALE_LEAVES = block(DistantWorldsModBlocks.FLOWERING_GARSALE_LEAVES);
	public static final RegistryObject<Item> GARSALE_VINES = block(DistantWorldsModBlocks.GARSALE_VINES);
	public static final RegistryObject<Item> FLOWERING_GARSALE_VINES = block(DistantWorldsModBlocks.FLOWERING_GARSALE_VINES);
	public static final RegistryObject<Item> GARSALE_LANTERN = block(DistantWorldsModBlocks.GARSALE_LANTERN);
	public static final RegistryObject<Item> STICKY_LAYERED_MUD = block(DistantWorldsModBlocks.STICKY_LAYERED_MUD);
	public static final RegistryObject<Item> COARSE_LAYERED_MUD = block(DistantWorldsModBlocks.COARSE_LAYERED_MUD);
	public static final RegistryObject<Item> COMPRESSED_LAYERED_MUD = block(DistantWorldsModBlocks.COMPRESSED_LAYERED_MUD);
	public static final RegistryObject<Item> GARSALE_WOOD = block(DistantWorldsModBlocks.GARSALE_WOOD);
	public static final RegistryObject<Item> GARSALE_LOG = block(DistantWorldsModBlocks.GARSALE_LOG);
	public static final RegistryObject<Item> CRACKED_GARSALE_LOG = block(DistantWorldsModBlocks.CRACKED_GARSALE_LOG);
	public static final RegistryObject<Item> STICKY_GARSALE_LOG = block(DistantWorldsModBlocks.STICKY_GARSALE_LOG);
	public static final RegistryObject<Item> STRIPPED_GARSALE_LOG = block(DistantWorldsModBlocks.STRIPPED_GARSALE_LOG);
	public static final RegistryObject<Item> STRIPPED_GARSALE_WOOD = block(DistantWorldsModBlocks.STRIPPED_GARSALE_WOOD);
	public static final RegistryObject<Item> GARSALE_PLANKS = block(DistantWorldsModBlocks.GARSALE_PLANKS);
	public static final RegistryObject<Item> GARSALE_STAIRS = block(DistantWorldsModBlocks.GARSALE_STAIRS);
	public static final RegistryObject<Item> GARSALE_SLAB = block(DistantWorldsModBlocks.GARSALE_SLAB);
	public static final RegistryObject<Item> GARSALE_DOOR = doubleBlock(DistantWorldsModBlocks.GARSALE_DOOR);
	public static final RegistryObject<Item> GARSALE_TRAPDOOR = block(DistantWorldsModBlocks.GARSALE_TRAPDOOR);
	public static final RegistryObject<Item> GARSALE_PANE = block(DistantWorldsModBlocks.GARSALE_PANE);
	public static final RegistryObject<Item> GARSALE_FENCE = block(DistantWorldsModBlocks.GARSALE_FENCE);
	public static final RegistryObject<Item> GARSALE_FENCE_GATE = block(DistantWorldsModBlocks.GARSALE_FENCE_GATE);
	public static final RegistryObject<Item> GARSALE_BUTTON = block(DistantWorldsModBlocks.GARSALE_BUTTON);
	public static final RegistryObject<Item> GARSALE_PRESSURE_PLATE = block(DistantWorldsModBlocks.GARSALE_PRESSURE_PLATE);
	public static final RegistryObject<Item> GARHENNA_RESEARCHES_TABLE = block(DistantWorldsModBlocks.GARHENNA_RESEARCHES_TABLE);
	public static final RegistryObject<Item> GARSALE_BOOKSHELF = block(DistantWorldsModBlocks.GARSALE_BOOKSHELF);
	public static final RegistryObject<Item> RED_GARSALE_COUCH = block(DistantWorldsModBlocks.RED_GARSALE_COUCH);
	public static final RegistryObject<Item> ORANGE_GARSALE_COUCH = block(DistantWorldsModBlocks.ORANGE_GARSALE_COUCH);
	public static final RegistryObject<Item> YELLOW_GARSALE_COUCH = block(DistantWorldsModBlocks.YELLOW_GARSALE_COUCH);
	public static final RegistryObject<Item> LIME_GARSALE_COUCH = block(DistantWorldsModBlocks.LIME_GARSALE_COUCH);
	public static final RegistryObject<Item> GREEN_GARSALE_COUCH = block(DistantWorldsModBlocks.GREEN_GARSALE_COUCH);
	public static final RegistryObject<Item> CYAN_GARSALE_COUCH = block(DistantWorldsModBlocks.CYAN_GARSALE_COUCH);
	public static final RegistryObject<Item> LIGHT_BLUE_GARSALE_COUCH = block(DistantWorldsModBlocks.LIGHT_BLUE_GARSALE_COUCH);
	public static final RegistryObject<Item> BLUE_GARSALE_COUCH = block(DistantWorldsModBlocks.BLUE_GARSALE_COUCH);
	public static final RegistryObject<Item> PURPLE_GARSALE_COUCH = block(DistantWorldsModBlocks.PURPLE_GARSALE_COUCH);
	public static final RegistryObject<Item> MAGENTA_GARSALE_COUCH = block(DistantWorldsModBlocks.MAGENTA_GARSALE_COUCH);
	public static final RegistryObject<Item> PINK_GARSALE_COUCH = block(DistantWorldsModBlocks.PINK_GARSALE_COUCH);
	public static final RegistryObject<Item> WHITE_GARSALE_COUCH = block(DistantWorldsModBlocks.WHITE_GARSALE_COUCH);
	public static final RegistryObject<Item> LIGHT_GRAY_GARSALE_COUCH = block(DistantWorldsModBlocks.LIGHT_GRAY_GARSALE_COUCH);
	public static final RegistryObject<Item> GRAY_GARSALE_COUCH = block(DistantWorldsModBlocks.GRAY_GARSALE_COUCH);
	public static final RegistryObject<Item> BLACK_GARSALE_COUCH = block(DistantWorldsModBlocks.BLACK_GARSALE_COUCH);
	public static final RegistryObject<Item> BROWN_GARSALE_COUCH = block(DistantWorldsModBlocks.BROWN_GARSALE_COUCH);
	public static final RegistryObject<Item> WITHERED_SOIL = block(DistantWorldsModBlocks.WITHERED_SOIL);
	public static final RegistryObject<Item> WITHERED_SPROUTS = block(DistantWorldsModBlocks.WITHERED_SPROUTS);
	public static final RegistryObject<Item> TALL_WITHERED_SPROUTS = doubleBlock(DistantWorldsModBlocks.TALL_WITHERED_SPROUTS);
	public static final RegistryObject<Item> ULBISEAF = block(DistantWorldsModBlocks.ULBISEAF);
	public static final RegistryObject<Item> CREWANOLLA = block(DistantWorldsModBlocks.CREWANOLLA);
	public static final RegistryObject<Item> CEBLUM = block(DistantWorldsModBlocks.CEBLUM);
	public static final RegistryObject<Item> RINYOT = block(DistantWorldsModBlocks.RINYOT);
	public static final RegistryObject<Item> OFYPLETTA = doubleBlock(DistantWorldsModBlocks.OFYPLETTA);
	public static final RegistryObject<Item> WOKAMIRE = block(DistantWorldsModBlocks.WOKAMIRE);
	public static final RegistryObject<Item> FUZIANNA = block(DistantWorldsModBlocks.FUZIANNA);
	public static final RegistryObject<Item> WILTUM_SAPLING = block(DistantWorldsModBlocks.WILTUM_SAPLING);
	public static final RegistryObject<Item> WILTUM_LEAVES = block(DistantWorldsModBlocks.WILTUM_LEAVES);
	public static final RegistryObject<Item> FLOWERING_WILTUM_LEAVES = block(DistantWorldsModBlocks.FLOWERING_WILTUM_LEAVES);
	public static final RegistryObject<Item> WILTUM_VINES = block(DistantWorldsModBlocks.WILTUM_VINES);
	public static final RegistryObject<Item> FLOWERING_WILTUM_VINES = block(DistantWorldsModBlocks.FLOWERING_WILTUM_VINES);
	public static final RegistryObject<Item> COARSE_WITHERED_SOIL = block(DistantWorldsModBlocks.COARSE_WITHERED_SOIL);
	public static final RegistryObject<Item> COMPRESSED_WITHERED_SOIL = block(DistantWorldsModBlocks.COMPRESSED_WITHERED_SOIL);
	public static final RegistryObject<Item> WILTUM_WOOD = block(DistantWorldsModBlocks.WILTUM_WOOD);
	public static final RegistryObject<Item> WILTUM_LOG = block(DistantWorldsModBlocks.WILTUM_LOG);
	public static final RegistryObject<Item> WILTUM_CORE = block(DistantWorldsModBlocks.WILTUM_CORE);
	public static final RegistryObject<Item> STRIPPED_WILTUM_LOG = block(DistantWorldsModBlocks.STRIPPED_WILTUM_LOG);
	public static final RegistryObject<Item> STRIPPED_WILTUM_WOOD = block(DistantWorldsModBlocks.STRIPPED_WILTUM_WOOD);
	public static final RegistryObject<Item> WILTUM_PLANKS = block(DistantWorldsModBlocks.WILTUM_PLANKS);
	public static final RegistryObject<Item> WILTUM_STAIRS = block(DistantWorldsModBlocks.WILTUM_STAIRS);
	public static final RegistryObject<Item> WILTUM_SLAB = block(DistantWorldsModBlocks.WILTUM_SLAB);
	public static final RegistryObject<Item> WILTUM_DOOR = doubleBlock(DistantWorldsModBlocks.WILTUM_DOOR);
	public static final RegistryObject<Item> WILTUM_TRAPDOOR = block(DistantWorldsModBlocks.WILTUM_TRAPDOOR);
	public static final RegistryObject<Item> WILTUM_PANE = block(DistantWorldsModBlocks.WILTUM_PANE);
	public static final RegistryObject<Item> WILTUM_FENCE = block(DistantWorldsModBlocks.WILTUM_FENCE);
	public static final RegistryObject<Item> WILTUM_FENCE_GATE = block(DistantWorldsModBlocks.WILTUM_FENCE_GATE);
	public static final RegistryObject<Item> WILTUM_BUTTON = block(DistantWorldsModBlocks.WILTUM_BUTTON);
	public static final RegistryObject<Item> WILTUM_PRESSURE_PLATE = block(DistantWorldsModBlocks.WILTUM_PRESSURE_PLATE);
	public static final RegistryObject<Item> RED_WILTUM_COUCH = block(DistantWorldsModBlocks.RED_WILTUM_COUCH);
	public static final RegistryObject<Item> ORANGE_WILTUM_COUCH = block(DistantWorldsModBlocks.ORANGE_WILTUM_COUCH);
	public static final RegistryObject<Item> YELLOW_WILTUM_COUCH = block(DistantWorldsModBlocks.YELLOW_WILTUM_COUCH);
	public static final RegistryObject<Item> LIME_WILTUM_COUCH = block(DistantWorldsModBlocks.LIME_WILTUM_COUCH);
	public static final RegistryObject<Item> GREEN_WILTUM_COUCH = block(DistantWorldsModBlocks.GREEN_WILTUM_COUCH);
	public static final RegistryObject<Item> CYAN_WILTUM_COUCH = block(DistantWorldsModBlocks.CYAN_WILTUM_COUCH);
	public static final RegistryObject<Item> LIGHT_BLUE_WILTUM_COUCH = block(DistantWorldsModBlocks.LIGHT_BLUE_WILTUM_COUCH);
	public static final RegistryObject<Item> BLUE_WILTUM_COUCH = block(DistantWorldsModBlocks.BLUE_WILTUM_COUCH);
	public static final RegistryObject<Item> PURPLE_WILTUM_COUCH = block(DistantWorldsModBlocks.PURPLE_WILTUM_COUCH);
	public static final RegistryObject<Item> MAGENTA_WILTUM_COUCH = block(DistantWorldsModBlocks.MAGENTA_WILTUM_COUCH);
	public static final RegistryObject<Item> PINK_WILTUM_COUCH = block(DistantWorldsModBlocks.PINK_WILTUM_COUCH);
	public static final RegistryObject<Item> WHITE_WILTUM_COUCH = block(DistantWorldsModBlocks.WHITE_WILTUM_COUCH);
	public static final RegistryObject<Item> LIGHT_GRAY_WILTUM_COUCH = block(DistantWorldsModBlocks.LIGHT_GRAY_WILTUM_COUCH);
	public static final RegistryObject<Item> GRAY_WILTUM_COUCH = block(DistantWorldsModBlocks.GRAY_WILTUM_COUCH);
	public static final RegistryObject<Item> BLACK_WILTUM_COUCH = block(DistantWorldsModBlocks.BLACK_WILTUM_COUCH);
	public static final RegistryObject<Item> BROWN_WILTUM_COUCH = block(DistantWorldsModBlocks.BROWN_WILTUM_COUCH);
	public static final RegistryObject<Item> OVERGROWN_FRALITE = block(DistantWorldsModBlocks.OVERGROWN_FRALITE);
	public static final RegistryObject<Item> MOLTEN_SPROUTS = block(DistantWorldsModBlocks.MOLTEN_SPROUTS);
	public static final RegistryObject<Item> TALL_MOLTEN_SPROUTS = doubleBlock(DistantWorldsModBlocks.TALL_MOLTEN_SPROUTS);
	public static final RegistryObject<Item> OTREBORE = block(DistantWorldsModBlocks.OTREBORE);
	public static final RegistryObject<Item> LIORESS = block(DistantWorldsModBlocks.LIORESS);
	public static final RegistryObject<Item> FLEMMAWIES = doubleBlock(DistantWorldsModBlocks.FLEMMAWIES);
	public static final RegistryObject<Item> CULAFITE_MUSHROOM = block(DistantWorldsModBlocks.CULAFITE_MUSHROOM);
	public static final RegistryObject<Item> CULAFITE_MUSHROOM_STEM = block(DistantWorldsModBlocks.CULAFITE_MUSHROOM_STEM);
	public static final RegistryObject<Item> CULAFITE_STEM_BLOCK = block(DistantWorldsModBlocks.CULAFITE_STEM_BLOCK);
	public static final RegistryObject<Item> CHISELED_CULAFITE_STEM = block(DistantWorldsModBlocks.CHISELED_CULAFITE_STEM);
	public static final RegistryObject<Item> CULAFITE_STEM_STAIRS = block(DistantWorldsModBlocks.CULAFITE_STEM_STAIRS);
	public static final RegistryObject<Item> CULAFITE_STEM_SLAB = block(DistantWorldsModBlocks.CULAFITE_STEM_SLAB);
	public static final RegistryObject<Item> CULAFITE_STEM_DOOR = doubleBlock(DistantWorldsModBlocks.CULAFITE_STEM_DOOR);
	public static final RegistryObject<Item> CULAFITE_STEM_TRAPDOOR = block(DistantWorldsModBlocks.CULAFITE_STEM_TRAPDOOR);
	public static final RegistryObject<Item> CULAFITE_STEM_PANE = block(DistantWorldsModBlocks.CULAFITE_STEM_PANE);
	public static final RegistryObject<Item> CULAFITE_MUSHROOM_BLOCK = block(DistantWorldsModBlocks.CULAFITE_MUSHROOM_BLOCK);
	public static final RegistryObject<Item> CULAFITE_SHROOMLIGHT = block(DistantWorldsModBlocks.CULAFITE_SHROOMLIGHT);
	public static final RegistryObject<Item> YAKNIR_ROOTS = block(DistantWorldsModBlocks.YAKNIR_ROOTS);
	public static final RegistryObject<Item> COBBLED_FRALITE = block(DistantWorldsModBlocks.COBBLED_FRALITE);
	public static final RegistryObject<Item> FRALITE = block(DistantWorldsModBlocks.FRALITE);
	public static final RegistryObject<Item> DALITE_ORE = block(DistantWorldsModBlocks.DALITE_ORE);
	public static final RegistryObject<Item> MOSSY_FRALITE = block(DistantWorldsModBlocks.MOSSY_FRALITE);
	public static final RegistryObject<Item> POLISHED_FRALITE = block(DistantWorldsModBlocks.POLISHED_FRALITE);
	public static final RegistryObject<Item> POLISHED_FRALITE_STAIRS = block(DistantWorldsModBlocks.POLISHED_FRALITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_FRALITE_SLAB = block(DistantWorldsModBlocks.POLISHED_FRALITE_SLAB);
	public static final RegistryObject<Item> POLISHED_FRALITE_WALL = block(DistantWorldsModBlocks.POLISHED_FRALITE_WALL);
	public static final RegistryObject<Item> FRALITE_BRICKS = block(DistantWorldsModBlocks.FRALITE_BRICKS);
	public static final RegistryObject<Item> FRALITE_BRICK_STAIRS = block(DistantWorldsModBlocks.FRALITE_BRICK_STAIRS);
	public static final RegistryObject<Item> FRALITE_BRICK_SLAB = block(DistantWorldsModBlocks.FRALITE_BRICK_SLAB);
	public static final RegistryObject<Item> FRALITE_BRICK_WALL = block(DistantWorldsModBlocks.FRALITE_BRICK_WALL);
	public static final RegistryObject<Item> CRACKED_FRALITE_BRICKS = block(DistantWorldsModBlocks.CRACKED_FRALITE_BRICKS);
	public static final RegistryObject<Item> MOSSY_FRALITE_BRICKS = block(DistantWorldsModBlocks.MOSSY_FRALITE_BRICKS);
	public static final RegistryObject<Item> FRALITE_COLUMN = block(DistantWorldsModBlocks.FRALITE_COLUMN);
	public static final RegistryObject<Item> FRALITE_FRAME = block(DistantWorldsModBlocks.FRALITE_FRAME);
	public static final RegistryObject<Item> FRALITE_TILES = block(DistantWorldsModBlocks.FRALITE_TILES);
	public static final RegistryObject<Item> MESHED_FRALITE = block(DistantWorldsModBlocks.MESHED_FRALITE);
	public static final RegistryObject<Item> FRALITE_LANTERN = block(DistantWorldsModBlocks.FRALITE_LANTERN);
	public static final RegistryObject<Item> POLISHED_FRALITE_BUTTON = block(DistantWorldsModBlocks.POLISHED_FRALITE_BUTTON);
	public static final RegistryObject<Item> POLISHED_FRALITE_PRESSURE_PLATE = block(DistantWorldsModBlocks.POLISHED_FRALITE_PRESSURE_PLATE);
	public static final RegistryObject<Item> COBBLED_REVELITE = block(DistantWorldsModBlocks.COBBLED_REVELITE);
	public static final RegistryObject<Item> REVELITE = block(DistantWorldsModBlocks.REVELITE);
	public static final RegistryObject<Item> CURELITE_ORE = block(DistantWorldsModBlocks.CURELITE_ORE);
	public static final RegistryObject<Item> FIRON_ORE = block(DistantWorldsModBlocks.FIRON_ORE);
	public static final RegistryObject<Item> MOSSY_REVELITE = block(DistantWorldsModBlocks.MOSSY_REVELITE);
	public static final RegistryObject<Item> POLISHED_REVELITE = block(DistantWorldsModBlocks.POLISHED_REVELITE);
	public static final RegistryObject<Item> POLISHED_REVELITE_STAIRS = block(DistantWorldsModBlocks.POLISHED_REVELITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_REVELITE_SLAB = block(DistantWorldsModBlocks.POLISHED_REVELITE_SLAB);
	public static final RegistryObject<Item> POLISHED_REVELITE_WALL = block(DistantWorldsModBlocks.POLISHED_REVELITE_WALL);
	public static final RegistryObject<Item> REVELITE_BRICKS = block(DistantWorldsModBlocks.REVELITE_BRICKS);
	public static final RegistryObject<Item> REVELITE_BRICK_STAIRS = block(DistantWorldsModBlocks.REVELITE_BRICK_STAIRS);
	public static final RegistryObject<Item> REVELITE_BRICK_SLAB = block(DistantWorldsModBlocks.REVELITE_BRICK_SLAB);
	public static final RegistryObject<Item> REVELITE_BRICK_WALL = block(DistantWorldsModBlocks.REVELITE_BRICK_WALL);
	public static final RegistryObject<Item> CRACKED_REVELITE_BRICKS = block(DistantWorldsModBlocks.CRACKED_REVELITE_BRICKS);
	public static final RegistryObject<Item> MOSSY_REVELITE_BRICKS = block(DistantWorldsModBlocks.MOSSY_REVELITE_BRICKS);
	public static final RegistryObject<Item> REVELITE_COLUMN = block(DistantWorldsModBlocks.REVELITE_COLUMN);
	public static final RegistryObject<Item> REVELITE_FRAME = block(DistantWorldsModBlocks.REVELITE_FRAME);
	public static final RegistryObject<Item> REVELITE_TILES = block(DistantWorldsModBlocks.REVELITE_TILES);
	public static final RegistryObject<Item> MESHED_REVELITE = block(DistantWorldsModBlocks.MESHED_REVELITE);
	public static final RegistryObject<Item> REVELITE_LANTERN = block(DistantWorldsModBlocks.REVELITE_LANTERN);
	public static final RegistryObject<Item> POLISHED_REVELITE_BUTTON = block(DistantWorldsModBlocks.POLISHED_REVELITE_BUTTON);
	public static final RegistryObject<Item> POLISHED_REVELITE_PRESSURE_PLATE = block(DistantWorldsModBlocks.POLISHED_REVELITE_PRESSURE_PLATE);
	public static final RegistryObject<Item> COBBLED_LITHUM = block(DistantWorldsModBlocks.COBBLED_LITHUM);
	public static final RegistryObject<Item> LITHUM = block(DistantWorldsModBlocks.LITHUM);
	public static final RegistryObject<Item> HELYST_ORE = block(DistantWorldsModBlocks.HELYST_ORE);
	public static final RegistryObject<Item> MOSSY_LITHUM = block(DistantWorldsModBlocks.MOSSY_LITHUM);
	public static final RegistryObject<Item> POLISHED_LITHUM = block(DistantWorldsModBlocks.POLISHED_LITHUM);
	public static final RegistryObject<Item> POLISHED_LITHUM_STAIRS = block(DistantWorldsModBlocks.POLISHED_LITHUM_STAIRS);
	public static final RegistryObject<Item> POLISHED_LITHUM_SLAB = block(DistantWorldsModBlocks.POLISHED_LITHUM_SLAB);
	public static final RegistryObject<Item> POLISHED_LITHUM_WALL = block(DistantWorldsModBlocks.POLISHED_LITHUM_WALL);
	public static final RegistryObject<Item> LITHUM_BRICKS = block(DistantWorldsModBlocks.LITHUM_BRICKS);
	public static final RegistryObject<Item> LITHUM_BRICK_STAIRS = block(DistantWorldsModBlocks.LITHUM_BRICK_STAIRS);
	public static final RegistryObject<Item> LITHUM_BRICK_SLAB = block(DistantWorldsModBlocks.LITHUM_BRICK_SLAB);
	public static final RegistryObject<Item> LITHUM_BRICK_WALL = block(DistantWorldsModBlocks.LITHUM_BRICK_WALL);
	public static final RegistryObject<Item> CRACKED_LITHUM_BRICKS = block(DistantWorldsModBlocks.CRACKED_LITHUM_BRICKS);
	public static final RegistryObject<Item> MOSSY_LITHUM_BRICKS = block(DistantWorldsModBlocks.MOSSY_LITHUM_BRICKS);
	public static final RegistryObject<Item> LITHUM_COLUMN = block(DistantWorldsModBlocks.LITHUM_COLUMN);
	public static final RegistryObject<Item> LITHUM_FRAME = block(DistantWorldsModBlocks.LITHUM_FRAME);
	public static final RegistryObject<Item> LITHUM_TILES = block(DistantWorldsModBlocks.LITHUM_TILES);
	public static final RegistryObject<Item> MESHED_LITHUM = block(DistantWorldsModBlocks.MESHED_LITHUM);
	public static final RegistryObject<Item> LITHUM_LANTERN = block(DistantWorldsModBlocks.LITHUM_LANTERN);
	public static final RegistryObject<Item> POLISHED_LITHUM_BUTTON = block(DistantWorldsModBlocks.POLISHED_LITHUM_BUTTON);
	public static final RegistryObject<Item> POLISHED_LITHUM_PRESSURE_PLATE = block(DistantWorldsModBlocks.POLISHED_LITHUM_PRESSURE_PLATE);
	public static final RegistryObject<Item> GLISTERING_LITHUM = block(DistantWorldsModBlocks.GLISTERING_LITHUM);
	public static final RegistryObject<Item> LITHUM_PEDESTAL = block(DistantWorldsModBlocks.LITHUM_PEDESTAL);
	public static final RegistryObject<Item> LITHUM_FURNACE = block(DistantWorldsModBlocks.LITHUM_FURNACE);
	public static final RegistryObject<Item> LITHUM_CONVERTER = block(DistantWorldsModBlocks.LITHUM_CONVERTER);
	public static final RegistryObject<Item> LITHUM_STORAGE_INITIAL = block(DistantWorldsModBlocks.LITHUM_STORAGE_INITIAL);
	public static final RegistryObject<Item> LITHUM_STORAGE_EXTENDED = block(DistantWorldsModBlocks.LITHUM_STORAGE_EXTENDED);
	public static final RegistryObject<Item> LITHUM_STORAGE_ADVANCED = block(DistantWorldsModBlocks.LITHUM_STORAGE_ADVANCED);
	public static final RegistryObject<Item> LITHUM_TRANSMITTER = block(DistantWorldsModBlocks.LITHUM_TRANSMITTER);
	public static final RegistryObject<Item> LITHUM_CORE = block(DistantWorldsModBlocks.LITHUM_CORE);
	public static final RegistryObject<Item> CULAFITE_MUSHROOM_ON_A_STICK = REGISTRY.register("culafite_mushroom_on_a_stick", () -> new CulafiteMushroomOnAStickItem());
	public static final RegistryObject<Item> FRALITE_SWORD = REGISTRY.register("fralite_sword", () -> new FraliteSwordItem());
	public static final RegistryObject<Item> FRALITE_PICKAXE = REGISTRY.register("fralite_pickaxe", () -> new FralitePickaxeItem());
	public static final RegistryObject<Item> FRALITE_AXE = REGISTRY.register("fralite_axe", () -> new FraliteAxeItem());
	public static final RegistryObject<Item> FRALITE_SHOVEL = REGISTRY.register("fralite_shovel", () -> new FraliteShovelItem());
	public static final RegistryObject<Item> FRALITE_HOE = REGISTRY.register("fralite_hoe", () -> new FraliteHoeItem());
	public static final RegistryObject<Item> REVELITE_SWORD = REGISTRY.register("revelite_sword", () -> new ReveliteSwordItem());
	public static final RegistryObject<Item> REVELITE_PICKAXE = REGISTRY.register("revelite_pickaxe", () -> new RevelitePickaxeItem());
	public static final RegistryObject<Item> REVELITE_AXE = REGISTRY.register("revelite_axe", () -> new ReveliteAxeItem());
	public static final RegistryObject<Item> REVELITE_SHOVEL = REGISTRY.register("revelite_shovel", () -> new ReveliteShovelItem());
	public static final RegistryObject<Item> REVELITE_HOE = REGISTRY.register("revelite_hoe", () -> new ReveliteHoeItem());
	public static final RegistryObject<Item> LITHUM_SWORD = REGISTRY.register("lithum_sword", () -> new LithumSwordItem());
	public static final RegistryObject<Item> LITHUM_PICKAXE = REGISTRY.register("lithum_pickaxe", () -> new LithumPickaxeItem());
	public static final RegistryObject<Item> LITHUM_AXE = REGISTRY.register("lithum_axe", () -> new LithumAxeItem());
	public static final RegistryObject<Item> LITHUM_SHOVEL = REGISTRY.register("lithum_shovel", () -> new LithumShovelItem());
	public static final RegistryObject<Item> LITHUM_HOE = REGISTRY.register("lithum_hoe", () -> new LithumHoeItem());
	public static final RegistryObject<Item> SALMORAN_ARMOR_HELMET = REGISTRY.register("salmoran_armor_helmet", () -> new SalmoranArmorItem.Helmet());
	public static final RegistryObject<Item> SALMORAN_ARMOR_CHESTPLATE = REGISTRY.register("salmoran_armor_chestplate", () -> new SalmoranArmorItem.Chestplate());
	public static final RegistryObject<Item> SALMORAN_ARMOR_LEGGINGS = REGISTRY.register("salmoran_armor_leggings", () -> new SalmoranArmorItem.Leggings());
	public static final RegistryObject<Item> SALMORAN_ARMOR_BOOTS = REGISTRY.register("salmoran_armor_boots", () -> new SalmoranArmorItem.Boots());
	public static final RegistryObject<Item> NOARHORN_AXE = REGISTRY.register("noarhorn_axe", () -> new NoarhornAxeItem());
	public static final RegistryObject<Item> NOARHORN_ARMOR_HELMET = REGISTRY.register("noarhorn_armor_helmet", () -> new NoarhornArmorItem.Helmet());
	public static final RegistryObject<Item> NOARHORN_ARMOR_CHESTPLATE = REGISTRY.register("noarhorn_armor_chestplate", () -> new NoarhornArmorItem.Chestplate());
	public static final RegistryObject<Item> NOARHORN_ARMOR_LEGGINGS = REGISTRY.register("noarhorn_armor_leggings", () -> new NoarhornArmorItem.Leggings());
	public static final RegistryObject<Item> NOARHORN_ARMOR_BOOTS = REGISTRY.register("noarhorn_armor_boots", () -> new NoarhornArmorItem.Boots());
	public static final RegistryObject<Item> UBRICITE_HAMMER = REGISTRY.register("ubricite_hammer", () -> new UbriciteHammerItem());
	public static final RegistryObject<Item> UBRICITE_ARMOR_HELMET = REGISTRY.register("ubricite_armor_helmet", () -> new UbriciteArmorItem.Helmet());
	public static final RegistryObject<Item> UBRICITE_ARMOR_CHESTPLATE = REGISTRY.register("ubricite_armor_chestplate", () -> new UbriciteArmorItem.Chestplate());
	public static final RegistryObject<Item> UBRICITE_ARMOR_LEGGINGS = REGISTRY.register("ubricite_armor_leggings", () -> new UbriciteArmorItem.Leggings());
	public static final RegistryObject<Item> UBRICITE_ARMOR_BOOTS = REGISTRY.register("ubricite_armor_boots", () -> new UbriciteArmorItem.Boots());
	public static final RegistryObject<Item> VAIRIS_SWORD = REGISTRY.register("vairis_sword", () -> new VairisSwordItem());
	public static final RegistryObject<Item> VAIRIS_HELMET = REGISTRY.register("vairis_helmet", () -> new VairisItem.Helmet());
	public static final RegistryObject<Item> VAIRIS_CHESTPLATE = REGISTRY.register("vairis_chestplate", () -> new VairisItem.Chestplate());
	public static final RegistryObject<Item> VAIRIS_LEGGINGS = REGISTRY.register("vairis_leggings", () -> new VairisItem.Leggings());
	public static final RegistryObject<Item> VAIRIS_BOOTS = REGISTRY.register("vairis_boots", () -> new VairisItem.Boots());
	public static final RegistryObject<Item> HELYST_SWORD = REGISTRY.register("helyst_sword", () -> new HelystSwordItem());
	public static final RegistryObject<Item> HELYST_PICKAXE = REGISTRY.register("helyst_pickaxe", () -> new HelystPickaxeItem());
	public static final RegistryObject<Item> HELYST_AXE = REGISTRY.register("helyst_axe", () -> new HelystAxeItem());
	public static final RegistryObject<Item> HELYST_SHOVEL = REGISTRY.register("helyst_shovel", () -> new HelystShovelItem());
	public static final RegistryObject<Item> HELYST_HOE = REGISTRY.register("helyst_hoe", () -> new HelystHoeItem());
	public static final RegistryObject<Item> HELYST_HELMET = REGISTRY.register("helyst_helmet", () -> new HelystItem.Helmet());
	public static final RegistryObject<Item> HELYST_CHESTPLATE = REGISTRY.register("helyst_chestplate", () -> new HelystItem.Chestplate());
	public static final RegistryObject<Item> HELYST_LEGGINGS = REGISTRY.register("helyst_leggings", () -> new HelystItem.Leggings());
	public static final RegistryObject<Item> HELYST_BOOTS = REGISTRY.register("helyst_boots", () -> new HelystItem.Boots());
	public static final RegistryObject<Item> FIRON_MULTITOOL = REGISTRY.register("firon_multitool", () -> new FironMultitoolItem());
	public static final RegistryObject<Item> FIRON_SWORD = REGISTRY.register("firon_sword", () -> new FironSwordItem());
	public static final RegistryObject<Item> FIRON_PICKAXE = REGISTRY.register("firon_pickaxe", () -> new FironPickaxeItem());
	public static final RegistryObject<Item> FIRON_AXE = REGISTRY.register("firon_axe", () -> new FironAxeItem());
	public static final RegistryObject<Item> FIRON_SHOVEL = REGISTRY.register("firon_shovel", () -> new FironShovelItem());
	public static final RegistryObject<Item> FIRON_HOE = REGISTRY.register("firon_hoe", () -> new FironHoeItem());
	public static final RegistryObject<Item> FIRON_HELMET = REGISTRY.register("firon_helmet", () -> new FironItem.Helmet());
	public static final RegistryObject<Item> FIRON_CHESTPLATE = REGISTRY.register("firon_chestplate", () -> new FironItem.Chestplate());
	public static final RegistryObject<Item> FIRON_LEGGINGS = REGISTRY.register("firon_leggings", () -> new FironItem.Leggings());
	public static final RegistryObject<Item> FIRON_BOOTS = REGISTRY.register("firon_boots", () -> new FironItem.Boots());
	public static final RegistryObject<Item> DRUTH_SPAWN_EGG = REGISTRY.register("druth_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.DRUTH, -7594971, -20674, new Item.Properties()));
	public static final RegistryObject<Item> CROUTHIL_SPAWN_EGG = REGISTRY.register("crouthil_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.CROUTHIL, -7594971, -20931, new Item.Properties()));
	public static final RegistryObject<Item> SHRULLOT_SPAWN_EGG = REGISTRY.register("shrullot_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.SHRULLOT, -7595228, -20931, new Item.Properties()));
	public static final RegistryObject<Item> BOOGLIAN_SPAWN_EGG = REGISTRY.register("booglian_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.BOOGLIAN, -8378860, -22016, new Item.Properties()));
	public static final RegistryObject<Item> CULAFITE_SHROOMER_SPAWN_EGG = REGISTRY.register("culafite_shroomer_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.CULAFITE_SHROOMER, -3830699, -7268292, new Item.Properties()));
	public static final RegistryObject<Item> BABY_NOARHORN_SPAWN_EGG = REGISTRY.register("baby_noarhorn_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.BABY_NOARHORN, -3789528, -11264240, new Item.Properties()));
	public static final RegistryObject<Item> NOARHORN_SPAWN_EGG = REGISTRY.register("noarhorn_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.NOARHORN, -4243649, -11855848, new Item.Properties()));
	public static final RegistryObject<Item> ARMORED_NOARHORN_SPAWN_EGG = REGISTRY.register("armored_noarhorn_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.ARMORED_NOARHORN, -2066170, -11855848, new Item.Properties()));
	public static final RegistryObject<Item> BABY_SALMORAN_SPAWN_EGG = REGISTRY.register("baby_salmoran_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.BABY_SALMORAN, -15395556, -11293222, new Item.Properties()));
	public static final RegistryObject<Item> SALMORAN_SPAWN_EGG = REGISTRY.register("salmoran_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.SALMORAN, -16747613, -14868434, new Item.Properties()));
	public static final RegistryObject<Item> ALPHA_SALMORAN_SPAWN_EGG = REGISTRY.register("alpha_salmoran_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.ALPHA_SALMORAN, -16713985, -13814962, new Item.Properties()));
	public static final RegistryObject<Item> TORAN_SPAWN_EGG = REGISTRY.register("toran_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.TORAN, -9886976, -42892, new Item.Properties()));
	public static final RegistryObject<Item> LOTERESS_SPAWN_EGG = REGISTRY.register("loteress_spawn_egg", () -> new ForgeSpawnEggItem(DistantWorldsModEntities.LOTERESS, -53936, -9952768, new Item.Properties()));
	public static final RegistryObject<Item> POTTED_GARSALE_SAPLING = block(DistantWorldsModBlocks.POTTED_GARSALE_SAPLING);
	public static final RegistryObject<Item> POTTED_WILTUM_SAPLING = block(DistantWorldsModBlocks.POTTED_WILTUM_SAPLING);
	public static final RegistryObject<Item> POTTED_AFOLLA = block(DistantWorldsModBlocks.POTTED_AFOLLA);
	public static final RegistryObject<Item> POTTED_WALIS = block(DistantWorldsModBlocks.POTTED_WALIS);
	public static final RegistryObject<Item> POTTED_SUWONNA = block(DistantWorldsModBlocks.POTTED_SUWONNA);
	public static final RegistryObject<Item> POTTED_APHLAVIS = block(DistantWorldsModBlocks.POTTED_APHLAVIS);
	public static final RegistryObject<Item> POTTED_CREWANOLLA = block(DistantWorldsModBlocks.POTTED_CREWANOLLA);
	public static final RegistryObject<Item> POTTED_CEBLUM = block(DistantWorldsModBlocks.POTTED_CEBLUM);
	public static final RegistryObject<Item> POTTED_RINYOT = block(DistantWorldsModBlocks.POTTED_RINYOT);
	public static final RegistryObject<Item> POTTED_CULAFITE_MUSHROOM = block(DistantWorldsModBlocks.POTTED_CULAFITE_MUSHROOM);
	public static final RegistryObject<Item> POTTED_IROTINE = block(DistantWorldsModBlocks.POTTED_IROTINE);
	public static final RegistryObject<Item> POTTED_LAFOSIA = block(DistantWorldsModBlocks.POTTED_LAFOSIA);
	public static final RegistryObject<Item> POTTED_LIORESS = block(DistantWorldsModBlocks.POTTED_LIORESS);
	public static final RegistryObject<Item> POTTED_PRIFONNA = block(DistantWorldsModBlocks.POTTED_PRIFONNA);
	public static final RegistryObject<Item> POTTED_FUZIANNA = block(DistantWorldsModBlocks.POTTED_FUZIANNA);
	public static final RegistryObject<Item> COMPLETED_GARHENNA_RESEARCHES = REGISTRY.register("completed_garhenna_researches", () -> new CompletedGarhennaResearchesItem());
	public static final RegistryObject<Item> POTTED_ULBISEAF = block(DistantWorldsModBlocks.POTTED_ULBISEAF);
	public static final RegistryObject<Item> GLOWING_POLLEN_BLOCK = block(DistantWorldsModBlocks.GLOWING_POLLEN_BLOCK);
	public static final RegistryObject<Item> POTTED_OTREBORE = block(DistantWorldsModBlocks.POTTED_OTREBORE);
	public static final RegistryObject<Item> CRACKED_SALMORAN_EGG = block(DistantWorldsModBlocks.CRACKED_SALMORAN_EGG);
	public static final RegistryObject<Item> DISTANT_WORLDS_BOOK = REGISTRY.register("distant_worlds_book", () -> new DistantWorldsBookItem());
	public static final RegistryObject<Item> GARHENNA_BOOK = REGISTRY.register("garhenna_book", () -> new GarhennaBookItem());
	public static final RegistryObject<Item> ASMULDA_BERRY_BUSH = block(DistantWorldsModBlocks.ASMULDA_BERRY_BUSH);
	public static final RegistryObject<Item> POTTED_ASMULDA_BERRY_BUSH = block(DistantWorldsModBlocks.POTTED_ASMULDA_BERRY_BUSH);
	public static final RegistryObject<Item> POTTED_WOKAMIRE = block(DistantWorldsModBlocks.POTTED_WOKAMIRE);
	public static final RegistryObject<Item> FRALITE_BALL = REGISTRY.register("fralite_ball", () -> new FraliteBallItem());
	public static final RegistryObject<Item> GARSALE_CRATE = REGISTRY.register("garsale_crate", () -> new GarsaleCrateItem());
	public static final RegistryObject<Item> WILTUM_CRATE = REGISTRY.register("wiltum_crate", () -> new WiltumCrateItem());
	public static final RegistryObject<Item> CAGED_GARSALE_LANTERN = block(DistantWorldsModBlocks.CAGED_GARSALE_LANTERN);
	public static final RegistryObject<Item> GLISTERING_WILTUM_FRUIT = REGISTRY.register("glistering_wiltum_fruit", () -> new GlisteringWiltumFruitItem());
	public static final RegistryObject<Item> GLISTERING_WILTUM_ELIXIR = REGISTRY.register("glistering_wiltum_elixir", () -> new GlisteringWiltumElixirItem());
	public static final RegistryObject<Item> CULAFITE_MUSHROOM_TALL = doubleBlock(DistantWorldsModBlocks.CULAFITE_MUSHROOM_TALL);
	public static final RegistryObject<Item> CURELITE_TORCH_GROUND = block(DistantWorldsModBlocks.CURELITE_TORCH_GROUND);
	public static final RegistryObject<Item> CURELITE_TORCH_WALL = block(DistantWorldsModBlocks.CURELITE_TORCH_WALL);
	public static final RegistryObject<Item> CURELITE_TORCH = REGISTRY.register("curelite_torch", () -> new CureliteTorchItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(GARSALE_CRATE.get(), new ResourceLocation("distant_worlds:garsale_crate_contains"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GarsaleCratePropertyValueProviderProcedure.execute(itemStackToRender));
			ItemProperties.register(WILTUM_CRATE.get(), new ResourceLocation("distant_worlds:wiltum_crate_contains"),
					(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) WiltumCratePropertyValueProviderProcedure.execute(itemStackToRender));
		});
	}
}
