
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.distantworlds.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.distantworlds.block.YellowWiltumCouchBlock;
import net.mcreator.distantworlds.block.YellowGarsaleCouchBlock;
import net.mcreator.distantworlds.block.YaknirRootsBlock;
import net.mcreator.distantworlds.block.WokamireBlock;
import net.mcreator.distantworlds.block.WitheredSproutsBlock;
import net.mcreator.distantworlds.block.WitheredSoilBlock;
import net.mcreator.distantworlds.block.WiltumWoodBlock;
import net.mcreator.distantworlds.block.WiltumVinesBlock;
import net.mcreator.distantworlds.block.WiltumTrapdoorBlock;
import net.mcreator.distantworlds.block.WiltumStairsBlock;
import net.mcreator.distantworlds.block.WiltumSlabBlock;
import net.mcreator.distantworlds.block.WiltumSaplingBlock;
import net.mcreator.distantworlds.block.WiltumPressurePlateBlock;
import net.mcreator.distantworlds.block.WiltumPlanksBlock;
import net.mcreator.distantworlds.block.WiltumPaneBlock;
import net.mcreator.distantworlds.block.WiltumLogBlock;
import net.mcreator.distantworlds.block.WiltumLeavesBlock;
import net.mcreator.distantworlds.block.WiltumFruitBoxBlock;
import net.mcreator.distantworlds.block.WiltumFenceGateBlock;
import net.mcreator.distantworlds.block.WiltumFenceBlock;
import net.mcreator.distantworlds.block.WiltumDoorBlock;
import net.mcreator.distantworlds.block.WiltumCoreBlock;
import net.mcreator.distantworlds.block.WiltumButtonBlock;
import net.mcreator.distantworlds.block.WhiteWiltumCouchBlock;
import net.mcreator.distantworlds.block.WhiteGarsaleCouchBlock;
import net.mcreator.distantworlds.block.WalisBlock;
import net.mcreator.distantworlds.block.VinrettyBlock;
import net.mcreator.distantworlds.block.VairisBlockBlock;
import net.mcreator.distantworlds.block.UlbiseafBlock;
import net.mcreator.distantworlds.block.TallWitheredSproutsBlock;
import net.mcreator.distantworlds.block.TallStickySproutsBlock;
import net.mcreator.distantworlds.block.TallMoltenSproutsBlock;
import net.mcreator.distantworlds.block.TallLifelessSproutsBlock;
import net.mcreator.distantworlds.block.SuwonnaBlock;
import net.mcreator.distantworlds.block.StrippedWiltumWoodBlock;
import net.mcreator.distantworlds.block.StrippedWiltumLogBlock;
import net.mcreator.distantworlds.block.StrippedGarsaleWoodBlock;
import net.mcreator.distantworlds.block.StrippedGarsaleLogBlock;
import net.mcreator.distantworlds.block.StickySproutsBlock;
import net.mcreator.distantworlds.block.StickyLayeredMudBlock;
import net.mcreator.distantworlds.block.StickyGarsaleLogBlock;
import net.mcreator.distantworlds.block.SalmoranEggBlock;
import net.mcreator.distantworlds.block.RinyotBlock;
import net.mcreator.distantworlds.block.ReveliteTilesBlock;
import net.mcreator.distantworlds.block.ReveliteLanternBlock;
import net.mcreator.distantworlds.block.ReveliteFrameBlock;
import net.mcreator.distantworlds.block.ReveliteColumnBlock;
import net.mcreator.distantworlds.block.ReveliteBricksBlock;
import net.mcreator.distantworlds.block.ReveliteBrickWallBlock;
import net.mcreator.distantworlds.block.ReveliteBrickStairsBlock;
import net.mcreator.distantworlds.block.ReveliteBrickSlabBlock;
import net.mcreator.distantworlds.block.ReveliteBlock;
import net.mcreator.distantworlds.block.RedWiltumCouchBlock;
import net.mcreator.distantworlds.block.RedGarsaleCouchBlock;
import net.mcreator.distantworlds.block.RawVairisBlockBlock;
import net.mcreator.distantworlds.block.RawHelystBlockBlock;
import net.mcreator.distantworlds.block.RawFironBlockBlock;
import net.mcreator.distantworlds.block.RawDaliteBlockBlock;
import net.mcreator.distantworlds.block.RawCureliteBlockBlock;
import net.mcreator.distantworlds.block.PurpleWiltumCouchBlock;
import net.mcreator.distantworlds.block.PurpleGarsaleCouchBlock;
import net.mcreator.distantworlds.block.PrifonnaBlock;
import net.mcreator.distantworlds.block.PottedWokamireBlock;
import net.mcreator.distantworlds.block.PottedWiltumSaplingBlock;
import net.mcreator.distantworlds.block.PottedWalisBlock;
import net.mcreator.distantworlds.block.PottedUlbiseafBlock;
import net.mcreator.distantworlds.block.PottedSuwonnaBlock;
import net.mcreator.distantworlds.block.PottedRinyotBlock;
import net.mcreator.distantworlds.block.PottedPrifonnaBlock;
import net.mcreator.distantworlds.block.PottedOtreboreBlock;
import net.mcreator.distantworlds.block.PottedLioressBlock;
import net.mcreator.distantworlds.block.PottedLafosiaBlock;
import net.mcreator.distantworlds.block.PottedIrotineBlock;
import net.mcreator.distantworlds.block.PottedGarsaleSaplingBlock;
import net.mcreator.distantworlds.block.PottedFuziannaBlock;
import net.mcreator.distantworlds.block.PottedCulafiteMushroomBlock;
import net.mcreator.distantworlds.block.PottedCrewanollaBlock;
import net.mcreator.distantworlds.block.PottedCeblumBlock;
import net.mcreator.distantworlds.block.PottedAsmuldaBerryBushBlock;
import net.mcreator.distantworlds.block.PottedAphlavisBlock;
import net.mcreator.distantworlds.block.PottedAfollaBlock;
import net.mcreator.distantworlds.block.PolishedReveliteWallBlock;
import net.mcreator.distantworlds.block.PolishedReveliteStairsBlock;
import net.mcreator.distantworlds.block.PolishedReveliteSlabBlock;
import net.mcreator.distantworlds.block.PolishedRevelitePressurePlateBlock;
import net.mcreator.distantworlds.block.PolishedReveliteButtonBlock;
import net.mcreator.distantworlds.block.PolishedReveliteBlock;
import net.mcreator.distantworlds.block.PolishedLithumWallBlock;
import net.mcreator.distantworlds.block.PolishedLithumStairsBlock;
import net.mcreator.distantworlds.block.PolishedLithumSlabBlock;
import net.mcreator.distantworlds.block.PolishedLithumPressurePlateBlock;
import net.mcreator.distantworlds.block.PolishedLithumButtonBlock;
import net.mcreator.distantworlds.block.PolishedLithumBlock;
import net.mcreator.distantworlds.block.PolishedFraliteWallBlock;
import net.mcreator.distantworlds.block.PolishedFraliteStairsBlock;
import net.mcreator.distantworlds.block.PolishedFraliteSlabBlock;
import net.mcreator.distantworlds.block.PolishedFralitePressurePlateBlock;
import net.mcreator.distantworlds.block.PolishedFraliteButtonBlock;
import net.mcreator.distantworlds.block.PolishedFraliteBlock;
import net.mcreator.distantworlds.block.PinkWiltumCouchBlock;
import net.mcreator.distantworlds.block.PinkGarsaleCouchBlock;
import net.mcreator.distantworlds.block.OvergrownFraliteBlock;
import net.mcreator.distantworlds.block.OtreboreBlock;
import net.mcreator.distantworlds.block.OrangeWiltumCouchBlock;
import net.mcreator.distantworlds.block.OrangeGarsaleCouchBlock;
import net.mcreator.distantworlds.block.OfyplettaBlock;
import net.mcreator.distantworlds.block.NoarhornSpikesBlockBlock;
import net.mcreator.distantworlds.block.MossyReveliteBricksBlock;
import net.mcreator.distantworlds.block.MossyReveliteBlock;
import net.mcreator.distantworlds.block.MossyLithumBricksBlock;
import net.mcreator.distantworlds.block.MossyLithumBlock;
import net.mcreator.distantworlds.block.MossyFraliteBricksBlock;
import net.mcreator.distantworlds.block.MossyFraliteBlock;
import net.mcreator.distantworlds.block.MoltenSproutsBlock;
import net.mcreator.distantworlds.block.MeshedReveliteBlock;
import net.mcreator.distantworlds.block.MeshedLithumBlock;
import net.mcreator.distantworlds.block.MeshedFraliteBlock;
import net.mcreator.distantworlds.block.MagentaWiltumCouchBlock;
import net.mcreator.distantworlds.block.MagentaGarsaleCouchBlock;
import net.mcreator.distantworlds.block.LithumTransmitterBlock;
import net.mcreator.distantworlds.block.LithumTilesBlock;
import net.mcreator.distantworlds.block.LithumStorageInitialBlock;
import net.mcreator.distantworlds.block.LithumStorageExtendedBlock;
import net.mcreator.distantworlds.block.LithumStorageAdvancedBlock;
import net.mcreator.distantworlds.block.LithumPedestalBlock;
import net.mcreator.distantworlds.block.LithumLanternBlock;
import net.mcreator.distantworlds.block.LithumFurnaceBlock;
import net.mcreator.distantworlds.block.LithumFrameBlock;
import net.mcreator.distantworlds.block.LithumCoreBlock;
import net.mcreator.distantworlds.block.LithumConverterBlock;
import net.mcreator.distantworlds.block.LithumColumnBlock;
import net.mcreator.distantworlds.block.LithumBricksBlock;
import net.mcreator.distantworlds.block.LithumBrickWallBlock;
import net.mcreator.distantworlds.block.LithumBrickStairsBlock;
import net.mcreator.distantworlds.block.LithumBrickSlabBlock;
import net.mcreator.distantworlds.block.LithumBlock;
import net.mcreator.distantworlds.block.LioressBlock;
import net.mcreator.distantworlds.block.LimeWiltumCouchBlock;
import net.mcreator.distantworlds.block.LimeGarsaleCouchBlock;
import net.mcreator.distantworlds.block.LightGrayWiltumCouchBlock;
import net.mcreator.distantworlds.block.LightGrayGarsaleCouchBlock;
import net.mcreator.distantworlds.block.LightBlueWiltumCouchBlock;
import net.mcreator.distantworlds.block.LightBlueGarsaleCouchBlock;
import net.mcreator.distantworlds.block.LifelessSproutsBlock;
import net.mcreator.distantworlds.block.LifelessGrassBlock;
import net.mcreator.distantworlds.block.LayeredMudBlock;
import net.mcreator.distantworlds.block.LafosiaBlock;
import net.mcreator.distantworlds.block.IrotineBlock;
import net.mcreator.distantworlds.block.HelystOreBlock;
import net.mcreator.distantworlds.block.HelystBlockBlock;
import net.mcreator.distantworlds.block.GreenWiltumCouchBlock;
import net.mcreator.distantworlds.block.GreenGarsaleCouchBlock;
import net.mcreator.distantworlds.block.GrayWiltumCouchBlock;
import net.mcreator.distantworlds.block.GrayGarsaleCouchBlock;
import net.mcreator.distantworlds.block.GlowingPollenBlockBlock;
import net.mcreator.distantworlds.block.GlisteringLithumBlock;
import net.mcreator.distantworlds.block.GlisteringGarsaleFruitBoxBlock;
import net.mcreator.distantworlds.block.GarsaleWoodBlock;
import net.mcreator.distantworlds.block.GarsaleVinesBlock;
import net.mcreator.distantworlds.block.GarsaleTrapdoorBlock;
import net.mcreator.distantworlds.block.GarsaleStairsBlock;
import net.mcreator.distantworlds.block.GarsaleSlabBlock;
import net.mcreator.distantworlds.block.GarsaleSaplingBlock;
import net.mcreator.distantworlds.block.GarsalePressurePlateBlock;
import net.mcreator.distantworlds.block.GarsalePlanksBlock;
import net.mcreator.distantworlds.block.GarsalePaneBlock;
import net.mcreator.distantworlds.block.GarsaleLogBlock;
import net.mcreator.distantworlds.block.GarsaleLeavesBlock;
import net.mcreator.distantworlds.block.GarsaleLanternBlock;
import net.mcreator.distantworlds.block.GarsaleFruitBoxBlock;
import net.mcreator.distantworlds.block.GarsaleFenceGateBlock;
import net.mcreator.distantworlds.block.GarsaleFenceBlock;
import net.mcreator.distantworlds.block.GarsaleDoorBlock;
import net.mcreator.distantworlds.block.GarsaleCakeBlock;
import net.mcreator.distantworlds.block.GarsaleButtonBlock;
import net.mcreator.distantworlds.block.GarsaleBookshelfBlock;
import net.mcreator.distantworlds.block.GarhennaResearchesTableBlock;
import net.mcreator.distantworlds.block.FuziannaBlock;
import net.mcreator.distantworlds.block.FraliteTilesBlock;
import net.mcreator.distantworlds.block.FraliteLanternBlock;
import net.mcreator.distantworlds.block.FraliteFrameBlock;
import net.mcreator.distantworlds.block.FraliteColumnBlock;
import net.mcreator.distantworlds.block.FraliteBricksBlock;
import net.mcreator.distantworlds.block.FraliteBrickWallBlock;
import net.mcreator.distantworlds.block.FraliteBrickStairsBlock;
import net.mcreator.distantworlds.block.FraliteBrickSlabBlock;
import net.mcreator.distantworlds.block.FraliteBlock;
import net.mcreator.distantworlds.block.FloweringWiltumVinesBlock;
import net.mcreator.distantworlds.block.FloweringWiltumLeavesBlock;
import net.mcreator.distantworlds.block.FloweringGarsaleVinesBlock;
import net.mcreator.distantworlds.block.FloweringGarsaleLeavesBlock;
import net.mcreator.distantworlds.block.FlemmawiesBlock;
import net.mcreator.distantworlds.block.FironOreBlock;
import net.mcreator.distantworlds.block.FironBlockBlock;
import net.mcreator.distantworlds.block.DaliteOreBlock;
import net.mcreator.distantworlds.block.DaliteBlockBlock;
import net.mcreator.distantworlds.block.CyanWiltumCouchBlock;
import net.mcreator.distantworlds.block.CyanGarsaleCouchBlock;
import net.mcreator.distantworlds.block.CureliteTorchWallBlock;
import net.mcreator.distantworlds.block.CureliteTorchGroundBlock;
import net.mcreator.distantworlds.block.CureliteOreBlock;
import net.mcreator.distantworlds.block.CureliteBlockBlock;
import net.mcreator.distantworlds.block.CulafiteStemTrapdoorBlock;
import net.mcreator.distantworlds.block.CulafiteStemStairsBlock;
import net.mcreator.distantworlds.block.CulafiteStemSlabBlock;
import net.mcreator.distantworlds.block.CulafiteStemPaneBlock;
import net.mcreator.distantworlds.block.CulafiteStemDoorBlock;
import net.mcreator.distantworlds.block.CulafiteStemBlockBlock;
import net.mcreator.distantworlds.block.CulafiteShroomlightBlock;
import net.mcreator.distantworlds.block.CulafiteMushroomsBoxBlock;
import net.mcreator.distantworlds.block.CulafiteMushroomTallBlock;
import net.mcreator.distantworlds.block.CulafiteMushroomStemBlock;
import net.mcreator.distantworlds.block.CulafiteMushroomBlockBlock;
import net.mcreator.distantworlds.block.CulafiteMushroomBlock;
import net.mcreator.distantworlds.block.CrewanollaBlock;
import net.mcreator.distantworlds.block.CrackedSalmoranEggBlock;
import net.mcreator.distantworlds.block.CrackedReveliteBricksBlock;
import net.mcreator.distantworlds.block.CrackedLithumBricksBlock;
import net.mcreator.distantworlds.block.CrackedGarsaleLogBlock;
import net.mcreator.distantworlds.block.CrackedFraliteBricksBlock;
import net.mcreator.distantworlds.block.CompressedWitheredSoilBlock;
import net.mcreator.distantworlds.block.CompressedLayeredMudBlock;
import net.mcreator.distantworlds.block.CobbledReveliteBlock;
import net.mcreator.distantworlds.block.CobbledLithumBlock;
import net.mcreator.distantworlds.block.CobbledFraliteBlock;
import net.mcreator.distantworlds.block.CoarseWitheredSoilBlock;
import net.mcreator.distantworlds.block.CoarseLayeredMudBlock;
import net.mcreator.distantworlds.block.ChiseledCulafiteStemBlock;
import net.mcreator.distantworlds.block.CeblumBlock;
import net.mcreator.distantworlds.block.CagedGarsaleLanternBlock;
import net.mcreator.distantworlds.block.BrownWiltumCouchBlock;
import net.mcreator.distantworlds.block.BrownGarsaleCouchBlock;
import net.mcreator.distantworlds.block.BlueWiltumCouchBlock;
import net.mcreator.distantworlds.block.BlueGarsaleCouchBlock;
import net.mcreator.distantworlds.block.BlackWiltumCouchBlock;
import net.mcreator.distantworlds.block.BlackGarsaleCouchBlock;
import net.mcreator.distantworlds.block.AsmuldaBerryBushBlock;
import net.mcreator.distantworlds.block.AsmuldaBerriesBoxBlock;
import net.mcreator.distantworlds.block.AphlavisBlock;
import net.mcreator.distantworlds.block.AnewortBlock;
import net.mcreator.distantworlds.block.AfollaBlock;
import net.mcreator.distantworlds.DistantWorldsMod;

public class DistantWorldsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, DistantWorldsMod.MODID);
	public static final RegistryObject<Block> ASMULDA_BERRIES_BOX = REGISTRY.register("asmulda_berries_box", () -> new AsmuldaBerriesBoxBlock());
	public static final RegistryObject<Block> GARSALE_CAKE = REGISTRY.register("garsale_cake", () -> new GarsaleCakeBlock());
	public static final RegistryObject<Block> GARSALE_FRUIT_BOX = REGISTRY.register("garsale_fruit_box", () -> new GarsaleFruitBoxBlock());
	public static final RegistryObject<Block> WILTUM_FRUIT_BOX = REGISTRY.register("wiltum_fruit_box", () -> new WiltumFruitBoxBlock());
	public static final RegistryObject<Block> CULAFITE_MUSHROOMS_BOX = REGISTRY.register("culafite_mushrooms_box", () -> new CulafiteMushroomsBoxBlock());
	public static final RegistryObject<Block> NOARHORN_SPIKES_BLOCK = REGISTRY.register("noarhorn_spikes_block", () -> new NoarhornSpikesBlockBlock());
	public static final RegistryObject<Block> SALMORAN_EGG = REGISTRY.register("salmoran_egg", () -> new SalmoranEggBlock());
	public static final RegistryObject<Block> RAW_VAIRIS_BLOCK = REGISTRY.register("raw_vairis_block", () -> new RawVairisBlockBlock());
	public static final RegistryObject<Block> VAIRIS_BLOCK = REGISTRY.register("vairis_block", () -> new VairisBlockBlock());
	public static final RegistryObject<Block> RAW_CURELITE_BLOCK = REGISTRY.register("raw_curelite_block", () -> new RawCureliteBlockBlock());
	public static final RegistryObject<Block> CURELITE_BLOCK = REGISTRY.register("curelite_block", () -> new CureliteBlockBlock());
	public static final RegistryObject<Block> RAW_DALITE_BLOCK = REGISTRY.register("raw_dalite_block", () -> new RawDaliteBlockBlock());
	public static final RegistryObject<Block> DALITE_BLOCK = REGISTRY.register("dalite_block", () -> new DaliteBlockBlock());
	public static final RegistryObject<Block> RAW_HELYST_BLOCK = REGISTRY.register("raw_helyst_block", () -> new RawHelystBlockBlock());
	public static final RegistryObject<Block> HELYST_BLOCK = REGISTRY.register("helyst_block", () -> new HelystBlockBlock());
	public static final RegistryObject<Block> RAW_FIRON_BLOCK = REGISTRY.register("raw_firon_block", () -> new RawFironBlockBlock());
	public static final RegistryObject<Block> FIRON_BLOCK = REGISTRY.register("firon_block", () -> new FironBlockBlock());
	public static final RegistryObject<Block> GLISTERING_GARSALE_FRUIT_BOX = REGISTRY.register("glistering_garsale_fruit_box", () -> new GlisteringGarsaleFruitBoxBlock());
	public static final RegistryObject<Block> LIFELESS_GRASS = REGISTRY.register("lifeless_grass", () -> new LifelessGrassBlock());
	public static final RegistryObject<Block> LIFELESS_SPROUTS = REGISTRY.register("lifeless_sprouts", () -> new LifelessSproutsBlock());
	public static final RegistryObject<Block> TALL_LIFELESS_SPROUTS = REGISTRY.register("tall_lifeless_sprouts", () -> new TallLifelessSproutsBlock());
	public static final RegistryObject<Block> AFOLLA = REGISTRY.register("afolla", () -> new AfollaBlock());
	public static final RegistryObject<Block> WALIS = REGISTRY.register("walis", () -> new WalisBlock());
	public static final RegistryObject<Block> SUWONNA = REGISTRY.register("suwonna", () -> new SuwonnaBlock());
	public static final RegistryObject<Block> APHLAVIS = REGISTRY.register("aphlavis", () -> new AphlavisBlock());
	public static final RegistryObject<Block> VINRETTY = REGISTRY.register("vinretty", () -> new VinrettyBlock());
	public static final RegistryObject<Block> LAYERED_MUD = REGISTRY.register("layered_mud", () -> new LayeredMudBlock());
	public static final RegistryObject<Block> STICKY_SPROUTS = REGISTRY.register("sticky_sprouts", () -> new StickySproutsBlock());
	public static final RegistryObject<Block> TALL_STICKY_SPROUTS = REGISTRY.register("tall_sticky_sprouts", () -> new TallStickySproutsBlock());
	public static final RegistryObject<Block> IROTINE = REGISTRY.register("irotine", () -> new IrotineBlock());
	public static final RegistryObject<Block> LAFOSIA = REGISTRY.register("lafosia", () -> new LafosiaBlock());
	public static final RegistryObject<Block> PRIFONNA = REGISTRY.register("prifonna", () -> new PrifonnaBlock());
	public static final RegistryObject<Block> ANEWORT = REGISTRY.register("anewort", () -> new AnewortBlock());
	public static final RegistryObject<Block> GARSALE_SAPLING = REGISTRY.register("garsale_sapling", () -> new GarsaleSaplingBlock());
	public static final RegistryObject<Block> GARSALE_LEAVES = REGISTRY.register("garsale_leaves", () -> new GarsaleLeavesBlock());
	public static final RegistryObject<Block> FLOWERING_GARSALE_LEAVES = REGISTRY.register("flowering_garsale_leaves", () -> new FloweringGarsaleLeavesBlock());
	public static final RegistryObject<Block> GARSALE_VINES = REGISTRY.register("garsale_vines", () -> new GarsaleVinesBlock());
	public static final RegistryObject<Block> FLOWERING_GARSALE_VINES = REGISTRY.register("flowering_garsale_vines", () -> new FloweringGarsaleVinesBlock());
	public static final RegistryObject<Block> GARSALE_LANTERN = REGISTRY.register("garsale_lantern", () -> new GarsaleLanternBlock());
	public static final RegistryObject<Block> STICKY_LAYERED_MUD = REGISTRY.register("sticky_layered_mud", () -> new StickyLayeredMudBlock());
	public static final RegistryObject<Block> COARSE_LAYERED_MUD = REGISTRY.register("coarse_layered_mud", () -> new CoarseLayeredMudBlock());
	public static final RegistryObject<Block> COMPRESSED_LAYERED_MUD = REGISTRY.register("compressed_layered_mud", () -> new CompressedLayeredMudBlock());
	public static final RegistryObject<Block> GARSALE_WOOD = REGISTRY.register("garsale_wood", () -> new GarsaleWoodBlock());
	public static final RegistryObject<Block> GARSALE_LOG = REGISTRY.register("garsale_log", () -> new GarsaleLogBlock());
	public static final RegistryObject<Block> CRACKED_GARSALE_LOG = REGISTRY.register("cracked_garsale_log", () -> new CrackedGarsaleLogBlock());
	public static final RegistryObject<Block> STICKY_GARSALE_LOG = REGISTRY.register("sticky_garsale_log", () -> new StickyGarsaleLogBlock());
	public static final RegistryObject<Block> STRIPPED_GARSALE_LOG = REGISTRY.register("stripped_garsale_log", () -> new StrippedGarsaleLogBlock());
	public static final RegistryObject<Block> STRIPPED_GARSALE_WOOD = REGISTRY.register("stripped_garsale_wood", () -> new StrippedGarsaleWoodBlock());
	public static final RegistryObject<Block> GARSALE_PLANKS = REGISTRY.register("garsale_planks", () -> new GarsalePlanksBlock());
	public static final RegistryObject<Block> GARSALE_STAIRS = REGISTRY.register("garsale_stairs", () -> new GarsaleStairsBlock());
	public static final RegistryObject<Block> GARSALE_SLAB = REGISTRY.register("garsale_slab", () -> new GarsaleSlabBlock());
	public static final RegistryObject<Block> GARSALE_DOOR = REGISTRY.register("garsale_door", () -> new GarsaleDoorBlock());
	public static final RegistryObject<Block> GARSALE_TRAPDOOR = REGISTRY.register("garsale_trapdoor", () -> new GarsaleTrapdoorBlock());
	public static final RegistryObject<Block> GARSALE_PANE = REGISTRY.register("garsale_pane", () -> new GarsalePaneBlock());
	public static final RegistryObject<Block> GARSALE_FENCE = REGISTRY.register("garsale_fence", () -> new GarsaleFenceBlock());
	public static final RegistryObject<Block> GARSALE_FENCE_GATE = REGISTRY.register("garsale_fence_gate", () -> new GarsaleFenceGateBlock());
	public static final RegistryObject<Block> GARSALE_BUTTON = REGISTRY.register("garsale_button", () -> new GarsaleButtonBlock());
	public static final RegistryObject<Block> GARSALE_PRESSURE_PLATE = REGISTRY.register("garsale_pressure_plate", () -> new GarsalePressurePlateBlock());
	public static final RegistryObject<Block> GARHENNA_RESEARCHES_TABLE = REGISTRY.register("garhenna_researches_table", () -> new GarhennaResearchesTableBlock());
	public static final RegistryObject<Block> GARSALE_BOOKSHELF = REGISTRY.register("garsale_bookshelf", () -> new GarsaleBookshelfBlock());
	public static final RegistryObject<Block> RED_GARSALE_COUCH = REGISTRY.register("red_garsale_couch", () -> new RedGarsaleCouchBlock());
	public static final RegistryObject<Block> ORANGE_GARSALE_COUCH = REGISTRY.register("orange_garsale_couch", () -> new OrangeGarsaleCouchBlock());
	public static final RegistryObject<Block> YELLOW_GARSALE_COUCH = REGISTRY.register("yellow_garsale_couch", () -> new YellowGarsaleCouchBlock());
	public static final RegistryObject<Block> LIME_GARSALE_COUCH = REGISTRY.register("lime_garsale_couch", () -> new LimeGarsaleCouchBlock());
	public static final RegistryObject<Block> GREEN_GARSALE_COUCH = REGISTRY.register("green_garsale_couch", () -> new GreenGarsaleCouchBlock());
	public static final RegistryObject<Block> CYAN_GARSALE_COUCH = REGISTRY.register("cyan_garsale_couch", () -> new CyanGarsaleCouchBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_GARSALE_COUCH = REGISTRY.register("light_blue_garsale_couch", () -> new LightBlueGarsaleCouchBlock());
	public static final RegistryObject<Block> BLUE_GARSALE_COUCH = REGISTRY.register("blue_garsale_couch", () -> new BlueGarsaleCouchBlock());
	public static final RegistryObject<Block> PURPLE_GARSALE_COUCH = REGISTRY.register("purple_garsale_couch", () -> new PurpleGarsaleCouchBlock());
	public static final RegistryObject<Block> MAGENTA_GARSALE_COUCH = REGISTRY.register("magenta_garsale_couch", () -> new MagentaGarsaleCouchBlock());
	public static final RegistryObject<Block> PINK_GARSALE_COUCH = REGISTRY.register("pink_garsale_couch", () -> new PinkGarsaleCouchBlock());
	public static final RegistryObject<Block> WHITE_GARSALE_COUCH = REGISTRY.register("white_garsale_couch", () -> new WhiteGarsaleCouchBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_GARSALE_COUCH = REGISTRY.register("light_gray_garsale_couch", () -> new LightGrayGarsaleCouchBlock());
	public static final RegistryObject<Block> GRAY_GARSALE_COUCH = REGISTRY.register("gray_garsale_couch", () -> new GrayGarsaleCouchBlock());
	public static final RegistryObject<Block> BLACK_GARSALE_COUCH = REGISTRY.register("black_garsale_couch", () -> new BlackGarsaleCouchBlock());
	public static final RegistryObject<Block> BROWN_GARSALE_COUCH = REGISTRY.register("brown_garsale_couch", () -> new BrownGarsaleCouchBlock());
	public static final RegistryObject<Block> WITHERED_SOIL = REGISTRY.register("withered_soil", () -> new WitheredSoilBlock());
	public static final RegistryObject<Block> WITHERED_SPROUTS = REGISTRY.register("withered_sprouts", () -> new WitheredSproutsBlock());
	public static final RegistryObject<Block> TALL_WITHERED_SPROUTS = REGISTRY.register("tall_withered_sprouts", () -> new TallWitheredSproutsBlock());
	public static final RegistryObject<Block> ULBISEAF = REGISTRY.register("ulbiseaf", () -> new UlbiseafBlock());
	public static final RegistryObject<Block> CREWANOLLA = REGISTRY.register("crewanolla", () -> new CrewanollaBlock());
	public static final RegistryObject<Block> CEBLUM = REGISTRY.register("ceblum", () -> new CeblumBlock());
	public static final RegistryObject<Block> RINYOT = REGISTRY.register("rinyot", () -> new RinyotBlock());
	public static final RegistryObject<Block> OFYPLETTA = REGISTRY.register("ofypletta", () -> new OfyplettaBlock());
	public static final RegistryObject<Block> WOKAMIRE = REGISTRY.register("wokamire", () -> new WokamireBlock());
	public static final RegistryObject<Block> FUZIANNA = REGISTRY.register("fuzianna", () -> new FuziannaBlock());
	public static final RegistryObject<Block> WILTUM_SAPLING = REGISTRY.register("wiltum_sapling", () -> new WiltumSaplingBlock());
	public static final RegistryObject<Block> WILTUM_LEAVES = REGISTRY.register("wiltum_leaves", () -> new WiltumLeavesBlock());
	public static final RegistryObject<Block> FLOWERING_WILTUM_LEAVES = REGISTRY.register("flowering_wiltum_leaves", () -> new FloweringWiltumLeavesBlock());
	public static final RegistryObject<Block> WILTUM_VINES = REGISTRY.register("wiltum_vines", () -> new WiltumVinesBlock());
	public static final RegistryObject<Block> FLOWERING_WILTUM_VINES = REGISTRY.register("flowering_wiltum_vines", () -> new FloweringWiltumVinesBlock());
	public static final RegistryObject<Block> COARSE_WITHERED_SOIL = REGISTRY.register("coarse_withered_soil", () -> new CoarseWitheredSoilBlock());
	public static final RegistryObject<Block> COMPRESSED_WITHERED_SOIL = REGISTRY.register("compressed_withered_soil", () -> new CompressedWitheredSoilBlock());
	public static final RegistryObject<Block> WILTUM_WOOD = REGISTRY.register("wiltum_wood", () -> new WiltumWoodBlock());
	public static final RegistryObject<Block> WILTUM_LOG = REGISTRY.register("wiltum_log", () -> new WiltumLogBlock());
	public static final RegistryObject<Block> WILTUM_CORE = REGISTRY.register("wiltum_core", () -> new WiltumCoreBlock());
	public static final RegistryObject<Block> STRIPPED_WILTUM_LOG = REGISTRY.register("stripped_wiltum_log", () -> new StrippedWiltumLogBlock());
	public static final RegistryObject<Block> STRIPPED_WILTUM_WOOD = REGISTRY.register("stripped_wiltum_wood", () -> new StrippedWiltumWoodBlock());
	public static final RegistryObject<Block> WILTUM_PLANKS = REGISTRY.register("wiltum_planks", () -> new WiltumPlanksBlock());
	public static final RegistryObject<Block> WILTUM_STAIRS = REGISTRY.register("wiltum_stairs", () -> new WiltumStairsBlock());
	public static final RegistryObject<Block> WILTUM_SLAB = REGISTRY.register("wiltum_slab", () -> new WiltumSlabBlock());
	public static final RegistryObject<Block> WILTUM_DOOR = REGISTRY.register("wiltum_door", () -> new WiltumDoorBlock());
	public static final RegistryObject<Block> WILTUM_TRAPDOOR = REGISTRY.register("wiltum_trapdoor", () -> new WiltumTrapdoorBlock());
	public static final RegistryObject<Block> WILTUM_PANE = REGISTRY.register("wiltum_pane", () -> new WiltumPaneBlock());
	public static final RegistryObject<Block> WILTUM_FENCE = REGISTRY.register("wiltum_fence", () -> new WiltumFenceBlock());
	public static final RegistryObject<Block> WILTUM_FENCE_GATE = REGISTRY.register("wiltum_fence_gate", () -> new WiltumFenceGateBlock());
	public static final RegistryObject<Block> WILTUM_BUTTON = REGISTRY.register("wiltum_button", () -> new WiltumButtonBlock());
	public static final RegistryObject<Block> WILTUM_PRESSURE_PLATE = REGISTRY.register("wiltum_pressure_plate", () -> new WiltumPressurePlateBlock());
	public static final RegistryObject<Block> RED_WILTUM_COUCH = REGISTRY.register("red_wiltum_couch", () -> new RedWiltumCouchBlock());
	public static final RegistryObject<Block> ORANGE_WILTUM_COUCH = REGISTRY.register("orange_wiltum_couch", () -> new OrangeWiltumCouchBlock());
	public static final RegistryObject<Block> YELLOW_WILTUM_COUCH = REGISTRY.register("yellow_wiltum_couch", () -> new YellowWiltumCouchBlock());
	public static final RegistryObject<Block> LIME_WILTUM_COUCH = REGISTRY.register("lime_wiltum_couch", () -> new LimeWiltumCouchBlock());
	public static final RegistryObject<Block> GREEN_WILTUM_COUCH = REGISTRY.register("green_wiltum_couch", () -> new GreenWiltumCouchBlock());
	public static final RegistryObject<Block> CYAN_WILTUM_COUCH = REGISTRY.register("cyan_wiltum_couch", () -> new CyanWiltumCouchBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_WILTUM_COUCH = REGISTRY.register("light_blue_wiltum_couch", () -> new LightBlueWiltumCouchBlock());
	public static final RegistryObject<Block> BLUE_WILTUM_COUCH = REGISTRY.register("blue_wiltum_couch", () -> new BlueWiltumCouchBlock());
	public static final RegistryObject<Block> PURPLE_WILTUM_COUCH = REGISTRY.register("purple_wiltum_couch", () -> new PurpleWiltumCouchBlock());
	public static final RegistryObject<Block> MAGENTA_WILTUM_COUCH = REGISTRY.register("magenta_wiltum_couch", () -> new MagentaWiltumCouchBlock());
	public static final RegistryObject<Block> PINK_WILTUM_COUCH = REGISTRY.register("pink_wiltum_couch", () -> new PinkWiltumCouchBlock());
	public static final RegistryObject<Block> WHITE_WILTUM_COUCH = REGISTRY.register("white_wiltum_couch", () -> new WhiteWiltumCouchBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_WILTUM_COUCH = REGISTRY.register("light_gray_wiltum_couch", () -> new LightGrayWiltumCouchBlock());
	public static final RegistryObject<Block> GRAY_WILTUM_COUCH = REGISTRY.register("gray_wiltum_couch", () -> new GrayWiltumCouchBlock());
	public static final RegistryObject<Block> BLACK_WILTUM_COUCH = REGISTRY.register("black_wiltum_couch", () -> new BlackWiltumCouchBlock());
	public static final RegistryObject<Block> BROWN_WILTUM_COUCH = REGISTRY.register("brown_wiltum_couch", () -> new BrownWiltumCouchBlock());
	public static final RegistryObject<Block> OVERGROWN_FRALITE = REGISTRY.register("overgrown_fralite", () -> new OvergrownFraliteBlock());
	public static final RegistryObject<Block> MOLTEN_SPROUTS = REGISTRY.register("molten_sprouts", () -> new MoltenSproutsBlock());
	public static final RegistryObject<Block> TALL_MOLTEN_SPROUTS = REGISTRY.register("tall_molten_sprouts", () -> new TallMoltenSproutsBlock());
	public static final RegistryObject<Block> OTREBORE = REGISTRY.register("otrebore", () -> new OtreboreBlock());
	public static final RegistryObject<Block> LIORESS = REGISTRY.register("lioress", () -> new LioressBlock());
	public static final RegistryObject<Block> FLEMMAWIES = REGISTRY.register("flemmawies", () -> new FlemmawiesBlock());
	public static final RegistryObject<Block> CULAFITE_MUSHROOM = REGISTRY.register("culafite_mushroom", () -> new CulafiteMushroomBlock());
	public static final RegistryObject<Block> CULAFITE_MUSHROOM_STEM = REGISTRY.register("culafite_mushroom_stem", () -> new CulafiteMushroomStemBlock());
	public static final RegistryObject<Block> CULAFITE_STEM_BLOCK = REGISTRY.register("culafite_stem_block", () -> new CulafiteStemBlockBlock());
	public static final RegistryObject<Block> CHISELED_CULAFITE_STEM = REGISTRY.register("chiseled_culafite_stem", () -> new ChiseledCulafiteStemBlock());
	public static final RegistryObject<Block> CULAFITE_STEM_STAIRS = REGISTRY.register("culafite_stem_stairs", () -> new CulafiteStemStairsBlock());
	public static final RegistryObject<Block> CULAFITE_STEM_SLAB = REGISTRY.register("culafite_stem_slab", () -> new CulafiteStemSlabBlock());
	public static final RegistryObject<Block> CULAFITE_STEM_DOOR = REGISTRY.register("culafite_stem_door", () -> new CulafiteStemDoorBlock());
	public static final RegistryObject<Block> CULAFITE_STEM_TRAPDOOR = REGISTRY.register("culafite_stem_trapdoor", () -> new CulafiteStemTrapdoorBlock());
	public static final RegistryObject<Block> CULAFITE_STEM_PANE = REGISTRY.register("culafite_stem_pane", () -> new CulafiteStemPaneBlock());
	public static final RegistryObject<Block> CULAFITE_MUSHROOM_BLOCK = REGISTRY.register("culafite_mushroom_block", () -> new CulafiteMushroomBlockBlock());
	public static final RegistryObject<Block> CULAFITE_SHROOMLIGHT = REGISTRY.register("culafite_shroomlight", () -> new CulafiteShroomlightBlock());
	public static final RegistryObject<Block> YAKNIR_ROOTS = REGISTRY.register("yaknir_roots", () -> new YaknirRootsBlock());
	public static final RegistryObject<Block> COBBLED_FRALITE = REGISTRY.register("cobbled_fralite", () -> new CobbledFraliteBlock());
	public static final RegistryObject<Block> FRALITE = REGISTRY.register("fralite", () -> new FraliteBlock());
	public static final RegistryObject<Block> DALITE_ORE = REGISTRY.register("dalite_ore", () -> new DaliteOreBlock());
	public static final RegistryObject<Block> MOSSY_FRALITE = REGISTRY.register("mossy_fralite", () -> new MossyFraliteBlock());
	public static final RegistryObject<Block> POLISHED_FRALITE = REGISTRY.register("polished_fralite", () -> new PolishedFraliteBlock());
	public static final RegistryObject<Block> POLISHED_FRALITE_STAIRS = REGISTRY.register("polished_fralite_stairs", () -> new PolishedFraliteStairsBlock());
	public static final RegistryObject<Block> POLISHED_FRALITE_SLAB = REGISTRY.register("polished_fralite_slab", () -> new PolishedFraliteSlabBlock());
	public static final RegistryObject<Block> POLISHED_FRALITE_WALL = REGISTRY.register("polished_fralite_wall", () -> new PolishedFraliteWallBlock());
	public static final RegistryObject<Block> FRALITE_BRICKS = REGISTRY.register("fralite_bricks", () -> new FraliteBricksBlock());
	public static final RegistryObject<Block> FRALITE_BRICK_STAIRS = REGISTRY.register("fralite_brick_stairs", () -> new FraliteBrickStairsBlock());
	public static final RegistryObject<Block> FRALITE_BRICK_SLAB = REGISTRY.register("fralite_brick_slab", () -> new FraliteBrickSlabBlock());
	public static final RegistryObject<Block> FRALITE_BRICK_WALL = REGISTRY.register("fralite_brick_wall", () -> new FraliteBrickWallBlock());
	public static final RegistryObject<Block> CRACKED_FRALITE_BRICKS = REGISTRY.register("cracked_fralite_bricks", () -> new CrackedFraliteBricksBlock());
	public static final RegistryObject<Block> MOSSY_FRALITE_BRICKS = REGISTRY.register("mossy_fralite_bricks", () -> new MossyFraliteBricksBlock());
	public static final RegistryObject<Block> FRALITE_COLUMN = REGISTRY.register("fralite_column", () -> new FraliteColumnBlock());
	public static final RegistryObject<Block> FRALITE_FRAME = REGISTRY.register("fralite_frame", () -> new FraliteFrameBlock());
	public static final RegistryObject<Block> FRALITE_TILES = REGISTRY.register("fralite_tiles", () -> new FraliteTilesBlock());
	public static final RegistryObject<Block> MESHED_FRALITE = REGISTRY.register("meshed_fralite", () -> new MeshedFraliteBlock());
	public static final RegistryObject<Block> FRALITE_LANTERN = REGISTRY.register("fralite_lantern", () -> new FraliteLanternBlock());
	public static final RegistryObject<Block> POLISHED_FRALITE_BUTTON = REGISTRY.register("polished_fralite_button", () -> new PolishedFraliteButtonBlock());
	public static final RegistryObject<Block> POLISHED_FRALITE_PRESSURE_PLATE = REGISTRY.register("polished_fralite_pressure_plate", () -> new PolishedFralitePressurePlateBlock());
	public static final RegistryObject<Block> COBBLED_REVELITE = REGISTRY.register("cobbled_revelite", () -> new CobbledReveliteBlock());
	public static final RegistryObject<Block> REVELITE = REGISTRY.register("revelite", () -> new ReveliteBlock());
	public static final RegistryObject<Block> CURELITE_ORE = REGISTRY.register("curelite_ore", () -> new CureliteOreBlock());
	public static final RegistryObject<Block> FIRON_ORE = REGISTRY.register("firon_ore", () -> new FironOreBlock());
	public static final RegistryObject<Block> MOSSY_REVELITE = REGISTRY.register("mossy_revelite", () -> new MossyReveliteBlock());
	public static final RegistryObject<Block> POLISHED_REVELITE = REGISTRY.register("polished_revelite", () -> new PolishedReveliteBlock());
	public static final RegistryObject<Block> POLISHED_REVELITE_STAIRS = REGISTRY.register("polished_revelite_stairs", () -> new PolishedReveliteStairsBlock());
	public static final RegistryObject<Block> POLISHED_REVELITE_SLAB = REGISTRY.register("polished_revelite_slab", () -> new PolishedReveliteSlabBlock());
	public static final RegistryObject<Block> POLISHED_REVELITE_WALL = REGISTRY.register("polished_revelite_wall", () -> new PolishedReveliteWallBlock());
	public static final RegistryObject<Block> REVELITE_BRICKS = REGISTRY.register("revelite_bricks", () -> new ReveliteBricksBlock());
	public static final RegistryObject<Block> REVELITE_BRICK_STAIRS = REGISTRY.register("revelite_brick_stairs", () -> new ReveliteBrickStairsBlock());
	public static final RegistryObject<Block> REVELITE_BRICK_SLAB = REGISTRY.register("revelite_brick_slab", () -> new ReveliteBrickSlabBlock());
	public static final RegistryObject<Block> REVELITE_BRICK_WALL = REGISTRY.register("revelite_brick_wall", () -> new ReveliteBrickWallBlock());
	public static final RegistryObject<Block> CRACKED_REVELITE_BRICKS = REGISTRY.register("cracked_revelite_bricks", () -> new CrackedReveliteBricksBlock());
	public static final RegistryObject<Block> MOSSY_REVELITE_BRICKS = REGISTRY.register("mossy_revelite_bricks", () -> new MossyReveliteBricksBlock());
	public static final RegistryObject<Block> REVELITE_COLUMN = REGISTRY.register("revelite_column", () -> new ReveliteColumnBlock());
	public static final RegistryObject<Block> REVELITE_FRAME = REGISTRY.register("revelite_frame", () -> new ReveliteFrameBlock());
	public static final RegistryObject<Block> REVELITE_TILES = REGISTRY.register("revelite_tiles", () -> new ReveliteTilesBlock());
	public static final RegistryObject<Block> MESHED_REVELITE = REGISTRY.register("meshed_revelite", () -> new MeshedReveliteBlock());
	public static final RegistryObject<Block> REVELITE_LANTERN = REGISTRY.register("revelite_lantern", () -> new ReveliteLanternBlock());
	public static final RegistryObject<Block> POLISHED_REVELITE_BUTTON = REGISTRY.register("polished_revelite_button", () -> new PolishedReveliteButtonBlock());
	public static final RegistryObject<Block> POLISHED_REVELITE_PRESSURE_PLATE = REGISTRY.register("polished_revelite_pressure_plate", () -> new PolishedRevelitePressurePlateBlock());
	public static final RegistryObject<Block> COBBLED_LITHUM = REGISTRY.register("cobbled_lithum", () -> new CobbledLithumBlock());
	public static final RegistryObject<Block> LITHUM = REGISTRY.register("lithum", () -> new LithumBlock());
	public static final RegistryObject<Block> HELYST_ORE = REGISTRY.register("helyst_ore", () -> new HelystOreBlock());
	public static final RegistryObject<Block> MOSSY_LITHUM = REGISTRY.register("mossy_lithum", () -> new MossyLithumBlock());
	public static final RegistryObject<Block> POLISHED_LITHUM = REGISTRY.register("polished_lithum", () -> new PolishedLithumBlock());
	public static final RegistryObject<Block> POLISHED_LITHUM_STAIRS = REGISTRY.register("polished_lithum_stairs", () -> new PolishedLithumStairsBlock());
	public static final RegistryObject<Block> POLISHED_LITHUM_SLAB = REGISTRY.register("polished_lithum_slab", () -> new PolishedLithumSlabBlock());
	public static final RegistryObject<Block> POLISHED_LITHUM_WALL = REGISTRY.register("polished_lithum_wall", () -> new PolishedLithumWallBlock());
	public static final RegistryObject<Block> LITHUM_BRICKS = REGISTRY.register("lithum_bricks", () -> new LithumBricksBlock());
	public static final RegistryObject<Block> LITHUM_BRICK_STAIRS = REGISTRY.register("lithum_brick_stairs", () -> new LithumBrickStairsBlock());
	public static final RegistryObject<Block> LITHUM_BRICK_SLAB = REGISTRY.register("lithum_brick_slab", () -> new LithumBrickSlabBlock());
	public static final RegistryObject<Block> LITHUM_BRICK_WALL = REGISTRY.register("lithum_brick_wall", () -> new LithumBrickWallBlock());
	public static final RegistryObject<Block> CRACKED_LITHUM_BRICKS = REGISTRY.register("cracked_lithum_bricks", () -> new CrackedLithumBricksBlock());
	public static final RegistryObject<Block> MOSSY_LITHUM_BRICKS = REGISTRY.register("mossy_lithum_bricks", () -> new MossyLithumBricksBlock());
	public static final RegistryObject<Block> LITHUM_COLUMN = REGISTRY.register("lithum_column", () -> new LithumColumnBlock());
	public static final RegistryObject<Block> LITHUM_FRAME = REGISTRY.register("lithum_frame", () -> new LithumFrameBlock());
	public static final RegistryObject<Block> LITHUM_TILES = REGISTRY.register("lithum_tiles", () -> new LithumTilesBlock());
	public static final RegistryObject<Block> MESHED_LITHUM = REGISTRY.register("meshed_lithum", () -> new MeshedLithumBlock());
	public static final RegistryObject<Block> LITHUM_LANTERN = REGISTRY.register("lithum_lantern", () -> new LithumLanternBlock());
	public static final RegistryObject<Block> POLISHED_LITHUM_BUTTON = REGISTRY.register("polished_lithum_button", () -> new PolishedLithumButtonBlock());
	public static final RegistryObject<Block> POLISHED_LITHUM_PRESSURE_PLATE = REGISTRY.register("polished_lithum_pressure_plate", () -> new PolishedLithumPressurePlateBlock());
	public static final RegistryObject<Block> GLISTERING_LITHUM = REGISTRY.register("glistering_lithum", () -> new GlisteringLithumBlock());
	public static final RegistryObject<Block> LITHUM_PEDESTAL = REGISTRY.register("lithum_pedestal", () -> new LithumPedestalBlock());
	public static final RegistryObject<Block> LITHUM_FURNACE = REGISTRY.register("lithum_furnace", () -> new LithumFurnaceBlock());
	public static final RegistryObject<Block> LITHUM_CONVERTER = REGISTRY.register("lithum_converter", () -> new LithumConverterBlock());
	public static final RegistryObject<Block> LITHUM_STORAGE_INITIAL = REGISTRY.register("lithum_storage_initial", () -> new LithumStorageInitialBlock());
	public static final RegistryObject<Block> LITHUM_STORAGE_EXTENDED = REGISTRY.register("lithum_storage_extended", () -> new LithumStorageExtendedBlock());
	public static final RegistryObject<Block> LITHUM_STORAGE_ADVANCED = REGISTRY.register("lithum_storage_advanced", () -> new LithumStorageAdvancedBlock());
	public static final RegistryObject<Block> LITHUM_TRANSMITTER = REGISTRY.register("lithum_transmitter", () -> new LithumTransmitterBlock());
	public static final RegistryObject<Block> LITHUM_CORE = REGISTRY.register("lithum_core", () -> new LithumCoreBlock());
	public static final RegistryObject<Block> CAGED_GARSALE_LANTERN = REGISTRY.register("caged_garsale_lantern", () -> new CagedGarsaleLanternBlock());
	public static final RegistryObject<Block> CULAFITE_MUSHROOM_TALL = REGISTRY.register("culafite_mushroom_tall", () -> new CulafiteMushroomTallBlock());
	public static final RegistryObject<Block> POTTED_GARSALE_SAPLING = REGISTRY.register("potted_garsale_sapling", () -> new PottedGarsaleSaplingBlock());
	public static final RegistryObject<Block> POTTED_WILTUM_SAPLING = REGISTRY.register("potted_wiltum_sapling", () -> new PottedWiltumSaplingBlock());
	public static final RegistryObject<Block> POTTED_AFOLLA = REGISTRY.register("potted_afolla", () -> new PottedAfollaBlock());
	public static final RegistryObject<Block> POTTED_WALIS = REGISTRY.register("potted_walis", () -> new PottedWalisBlock());
	public static final RegistryObject<Block> POTTED_SUWONNA = REGISTRY.register("potted_suwonna", () -> new PottedSuwonnaBlock());
	public static final RegistryObject<Block> POTTED_APHLAVIS = REGISTRY.register("potted_aphlavis", () -> new PottedAphlavisBlock());
	public static final RegistryObject<Block> POTTED_CREWANOLLA = REGISTRY.register("potted_crewanolla", () -> new PottedCrewanollaBlock());
	public static final RegistryObject<Block> POTTED_CEBLUM = REGISTRY.register("potted_ceblum", () -> new PottedCeblumBlock());
	public static final RegistryObject<Block> POTTED_RINYOT = REGISTRY.register("potted_rinyot", () -> new PottedRinyotBlock());
	public static final RegistryObject<Block> POTTED_CULAFITE_MUSHROOM = REGISTRY.register("potted_culafite_mushroom", () -> new PottedCulafiteMushroomBlock());
	public static final RegistryObject<Block> POTTED_IROTINE = REGISTRY.register("potted_irotine", () -> new PottedIrotineBlock());
	public static final RegistryObject<Block> POTTED_LAFOSIA = REGISTRY.register("potted_lafosia", () -> new PottedLafosiaBlock());
	public static final RegistryObject<Block> POTTED_LIORESS = REGISTRY.register("potted_lioress", () -> new PottedLioressBlock());
	public static final RegistryObject<Block> POTTED_PRIFONNA = REGISTRY.register("potted_prifonna", () -> new PottedPrifonnaBlock());
	public static final RegistryObject<Block> POTTED_FUZIANNA = REGISTRY.register("potted_fuzianna", () -> new PottedFuziannaBlock());
	public static final RegistryObject<Block> POTTED_ULBISEAF = REGISTRY.register("potted_ulbiseaf", () -> new PottedUlbiseafBlock());
	public static final RegistryObject<Block> GLOWING_POLLEN_BLOCK = REGISTRY.register("glowing_pollen_block", () -> new GlowingPollenBlockBlock());
	public static final RegistryObject<Block> POTTED_OTREBORE = REGISTRY.register("potted_otrebore", () -> new PottedOtreboreBlock());
	public static final RegistryObject<Block> CRACKED_SALMORAN_EGG = REGISTRY.register("cracked_salmoran_egg", () -> new CrackedSalmoranEggBlock());
	public static final RegistryObject<Block> ASMULDA_BERRY_BUSH = REGISTRY.register("asmulda_berry_bush", () -> new AsmuldaBerryBushBlock());
	public static final RegistryObject<Block> POTTED_ASMULDA_BERRY_BUSH = REGISTRY.register("potted_asmulda_berry_bush", () -> new PottedAsmuldaBerryBushBlock());
	public static final RegistryObject<Block> POTTED_WOKAMIRE = REGISTRY.register("potted_wokamire", () -> new PottedWokamireBlock());
	public static final RegistryObject<Block> CURELITE_TORCH_GROUND = REGISTRY.register("curelite_torch_ground", () -> new CureliteTorchGroundBlock());
	public static final RegistryObject<Block> CURELITE_TORCH_WALL = REGISTRY.register("curelite_torch_wall", () -> new CureliteTorchWallBlock());
}
